### ISSUE TITLE
easyrtc: enable audio receive even if no getMediaStream supported

### ISSUE THREAD

**Issue by antoniohof** [networked-aframe/networked-aframe#101]
I suggest setting `this.easyrtc.enableAudioReceive(true);` as peers should always receive audio, regardless of them having access to mic or a supported browser.

This change includes setting the 	      `this.easyrtc.setStreamAcceptor(this._storeAudioStream.bind(this));
` 
outside the _connectWithAudio function, as it must be set even if you didnt connect with audio: true.

**Comment by antoniohof** [comment]
I will make a pull request on the weekend.

**Comment by antoniohof** [comment]
I'm working on a pull request

**Comment by haydenjameslee** [comment]
Awesome, that make sense.

**Comment by antoniohof** [comment]
https://github.com/networked-aframe/networked-aframe/pull/159

**Comment by haydenjameslee** [comment]
Merged. I appreciate the PR!
