### ISSUE TITLE
No error is logged when an incorrect serverURL is set

### ISSUE THREAD

**Issue by haydenjameslee** [networked-aframe/networked-aframe#107]

**Comment by hthetiot** [comment]
Should be fixed by #175 Open-easyRTC migration.
Otherwise may be fixed with incoming fix from open-easyrtc here: https://github.com/open-easyrtc/open-easyrtc/pull/26

**Comment by vincentfretin** [comment]
Ok, see https://github.com/networked-aframe/networked-aframe/issues/240#issuecomment-784487989
