### ISSUE TITLE
Worked last week having problem this week

### ISSUE THREAD

**Issue by pmedlock** [networked-aframe/networked-aframe#119]
Hello,
My NodeJS server (xj.yancich.com:3400) uses your menu, I'm adding additional stuff to it as I go. Was running fine late last week, but not so much this morning. I've tried several of both your examples and mine.  Same problem. Here is what I see in the console log:

11:27:00.517 A-Frame Version: 0.7.0 (Date 22-09-2017, Commit #570c623e)
index.js:86
11:27:00.517 three Version: ^0.87.0
index.js:87
11:27:00.518 WebVR Polyfill Version: ^0.9.36
index.js:88
11:27:00.556 THREE.WebGLRenderer 87
three.js:20919:2
11:27:00.668 core:schema:warn Unknown property `showLocalTemplate` for component/system `networked`. 
browser.js:111:7
11:27:00.669
template el for #avatar-template is not cached, register template with NAF.schemas.add.
networked-aframe.min.js:1:11824
11:27:00.671
template el for  is not cached, register template with NAF.schemas.add.
networked-aframe.min.js:1:11824
11:27:00.673 TypeError: this.templateCache[t] is undefined[Learn More]
networked-aframe.min.js:1:21741
11:27:00.673
template el for  is not cached, register template with NAF.schemas.add.
networked-aframe.min.js:1:11824

Here is the JavaScript I am importing in one of my (failing) examples (xj.yancich.com:3400/env01.html):

  <head>
     <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.js"></script>
     <script src="https://aframe.io/releases/0.7.0/aframe.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.5/socket.io.min.js"></script>
     <script src="easyrtc/easyrtc.js"></script>
     <script src="./js/aframe-environment-component.js"></script>
     <script src="https://unpkg.com/networked-aframe/dist/networked-aframe.min.js"></script>
     <script src="https://unpkg.com/aframe-randomizer-components@^3.0.1/dist/aframe-randomizer-components.min.js"></script>
      
     
     <script src="./js/mycode.js"></script>

etc...

It's a great addition to the NPM library; I can do a lot even as I'm learning.

Thanks for your work
Paul Medlock

**Comment by haydenjameslee** [comment]
Hi Paul,

We just released version 0.6 of Networked-Aframe and it has some breaking changes. This means you'll have to update your project. Here's what you have to change: https://github.com/networked-aframe/networked-aframe/blob/master/docs/RELEASE_NOTES.md#060

If you don't wish to update however you can specify the version number explicitly which will prevent this sort of problem happening again. When referencing the NAF source use this link instead: `https://unpkg.com/networked-aframe@^0.5.2/dist/networked-aframe.min.js` and that will keep you on 0.5 versions.
