### ISSUE TITLE
Adding scale to default sync component in schema

### ISSUE THREAD

**Issue by rrrepos** [networked-aframe/networked-aframe#120]
It will be convenient if the `scale` component could be added to the existing, `position` and `rotation` as default components of a schema which get sync'd.

**Comment by vincentfretin** [comment]
I don't think synchronizing scale is good as default, it's will generally not be used and so send extra info we don't need over the wire, although the message is well optimized and it won't send update for the component if it didn't changed I think.
Anyway it will be a breaking change to do that now.
If you really need to sync scale, you can create a specific schema.
