### ISSUE TITLE
Template validation fails in Edge

### ISSUE THREAD

**Issue by wmurphyrd** [networked-aframe/networked-aframe#129]
NAF throws the "Templates must have on direct child element" error even on valid templates in MS Edge

https://github.com/networked-aframe/networked-aframe/blob/d446aa54f79860809fb8bcaf22b4f6114a14aaff/src/Schemas.js#L93

`Template.content.childElementCount` is undefined in Edge, causing the check to always fail. Due to #98, logging the error message also crashes the entire script.

**Comment by wmurphyrd** [comment]
Here's why:

https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment#Browser_compatibility

Not all of the ParentNode interface is implemented for DocumentFragment in Edge. 

Both of these alternatives are working in Edge:

`el.content.querySelectorAll('*').length`

`el.content.children.length`

**Comment by wmurphyrd** [comment]
This is fixed in the most recent version of Edge (windows 10 v1803, build 17134.81)

**Comment by haydenjameslee** [comment]
Thanks for this investigation
