### ISSUE TITLE
Add support for gltf avatar templates

### ISSUE THREAD

**Issue by jamesdeantv** [networked-aframe/networked-aframe#132]
I would like to create a pull request to add animated models to NAF.  However, I will need to do a bit of research before I can create one.  So, I figured I would ask here before I went down the hole... How would I go about including an animated gltf or blender json model to the scene in place of the sphere entity?

**Comment by haydenjameslee** [comment]
It's possible to add gltf's without changing the NAF codebase, so a PR shouldn't be necessary (although I'm open to the idea of adding it if you have an interesting idea of how it could be integrated). It should be as simple as:

```
<a-assets>
    <a-asset-item id="avatar" src="/path/to/avatar.gltf"></a-asset-item>

    <template id="avatar-template">
        <a-entity gltf-model="#avatar"></a-entity>
    </template>
</a-assets>

```
