### ISSUE TITLE
Can I use a WebSocket server developed by me?

### ISSUE THREAD

**Issue by tauroamp** [networked-aframe/networked-aframe#133]
Hello!
We are a team of virtual reality applications development on web.
We want to use the networked-aframe component as part of one of our projects. It complies with everything we need, but in the examples it uses a server developed by a third party.
Currently, we have developed our own  websockets server on Java and we would like to know what structure messages must be sent to the server, and those that are returned to the client, to make this component work within A-Frame using the server developed for our team.
Is it possible to help us with that information?
I want to thank you in advance.

**Comment by poVoq** [comment]
A XMPP websocket adapter would be awesome. That would also allow to use Videobridge for efficient forwarding of webrtc multi user streams (as used in Jitsi Meet).

**Comment by poVoq** [comment]
https://github.com/legastero/stanza
Might be an easy way to do it?

**Comment by vincentfretin** [comment]
You are free to develop your own adapters based on any server you want. :-) Look at the different adapters implementation for inspiration.
