### ISSUE TITLE
On 'Getting started with Networked-Aframe' please add command for Linux OS

### ISSUE THREAD

**Issue by AlbirrKarim** [networked-aframe/networked-aframe#135]
![screenshot_2018-07-06_13-38-44](https://user-images.githubusercontent.com/29292018/42363569-5d192c52-8122-11e8-9ad5-db76450d3c58.png)
https://github.com/networked-aframe/networked-aframe/blob/master/docs/getting-started-local.md
Please add command for Linux OS because many programmer also use linux especially Ubuntu
Cheers,
Albirr

**Comment by haydenjameslee** [comment]
I've never tested it with Linux, have you had any success getting it working? Would be cool to hear.

**Comment by vincentfretin** [comment]
I'm using Linux and followed the getting started doc without issue. Linux commands are exactly the same commands than MacOS.

**Comment by haydenjameslee** [comment]
Added: https://github.com/networked-aframe/networked-aframe/commit/19d523ddeddc7f945d0d0eab4bde1f5c48ff2233
