### ISSUE TITLE
easyrtc: Rendering stopped when on sync-message error

### ISSUE THREAD

**Issue by mstrewe** [networked-aframe/networked-aframe#138]
I used networked-aframe for a test with 9 participants. We encountered, that as more network clients are connected the scene freezes (android smarphones). 

What happened is, an error at the method sendData (line 5823) of the easyrtc.js was fired and this caused the renderloop of threejs to stop. I fixed it with a try catch in the sendDate method of easyrtc.js. I think there is a better solution for that.

**Comment by haydenjameslee** [comment]
Hmm I haven't heard of this happening and we have had people using easyrtc with more than 9 participants. Maybe it's an android issue however. Is your project public?

**Comment by mstrewe** [comment]
Yes it ist. https://github.com/mstrewe/master-thesis.

The master branch has the issue with freezing visuals. The branch fix_perf_only_easyrtc has the try catch in the send data method.

**Comment by vincentfretin** [comment]
Please test again with open-easyrtc, see https://github.com/networked-aframe/networked-aframe/issues/240#issuecomment-784487989
Reopen if it's still an issue.
