### ISSUE TITLE
Touch controls not updating avatar position

### ISSUE THREAD

**Issue by TheBiggestNumber** [networked-aframe/networked-aframe#143]
Movement-controls (aframe-extras) added to "player" entity.
Using touch-controls on iOS moves player forward in scene.
However, other players do not see avatar change position (rotation is tracked ok though).

**Comment by haydenjameslee** [comment]
Could you post the example code or a link to a glitch project?

**Comment by TheBiggestNumber** [comment]
Seems to be working now. Thanks!

**Comment by TheBiggestNumber** [comment]
Hi. This issue has re-appeared:
https://gigantic-paper.glitch.me

iOS users' avatars stay in the same location.
They can rotate and do see other avatars move, but their avatars don't move.

**Comment by haydenjameslee** [comment]
Please update to Networked-Aframe ^0.6.2, you are two major releases behind and it will be very hard to track and fix bugs from that long ago.

**Comment by TheBiggestNumber** [comment]
Hi. I tried, but with that version, the iOS avatars actually disappear.
I have found a solution to the iOS avatar movement issue by using the below controls.
https://github.com/Ctrl-Alt-Zen/aframe-mobile-controls
