### ISSUE TITLE
Possible to dynamically add and sync a component on an already-synced entity?

### ISSUE THREAD

**Issue by twastvedt** [networked-aframe/networked-aframe#154]
I'm interested in finding a way to do this generally, but to provide a specific use case: I'm creating a drawing program where one of the features is to make boxes, and then optionally apply a subdivision modifier to one of the created boxes. So, I can add an entity that is synced using the `networked` component, which applies a template which adds a box to the scene:

    <template id="box-template">
        <a-entity>
            <a-box></a-box>
        </a-entity>
    </template>

    <a-entity networked="#box-template"></a-entity>

So far so good. I would now like to be able to add and sync a subdivision component that I have written on that entity. Is there a way to do this? It looks like if I add the subdivision component to the template but it doesn't exist on the entity from the beginning, nothing syncs. I've also tried adding a schema (and an empty template in the HTML) to the subdivision component and dynamically adding it to the `a-box`:

    NAFSchema: {
		template: '#subdivision-template',
		components: [
			'position',
			'rotation',
			'scale',
			'subdivision'
		]
	},

When I do this a new `a-entity` is created and synced as a sibling to the `a-box` in the other clients instead of the subdivision component going on the `a-box`.

I'd also prefer not to modify the box template dynamically (if that's even possible), as there are other entities that will be using the template without the subdivision component.

**Comment by vincentfretin** [comment]
It's hard to help you without the full code of what you trying to achieve. If you can create a small example on glitch.com with your issue, I'll gladly help.
It's been more than two years now, so I'll close. Please reopen you're still working on it. :)
