### ISSUE TITLE
`networked-audio-source` is not movable in Aframe `0.9.0`

### ISSUE THREAD

**Issue by dsinni** [networked-aframe/networked-aframe#156]
The `networked-audio-source` doesn't appear to move with the avatar in A-Frame `0.9.0` as it does in A-Frame `0.8.*`.

The source seems to stay anchored at `0 0 0`, regardless of movement, yet it _is_ "positional" in terms of direction and distance.

**Comment by dsinni** [comment]
This also appears to be true for the MozillaReality fork, if anyone is watching. :)

**Comment by dsinni** [comment]
This may have to do with changes in how audio is handled between `0.8.2` and `0.9.0`.

I _do_ know that changes were made to bring back support for audio instancing (multiple entities using the same audio source), which was a regression in `0.8.2` due to changes in Three.js. A-Frame `0.9.0` fixed this issue.

**Comment by vincentfretin** [comment]
I use aframe 1.0.4 and mozilla fork in a project. I don't have an issue with positional audio. Be sure to set the `networked-audio-source` component where you sync the camera position for the avatar though.
