### ISSUE TITLE
Oculus go movement

### ISSUE THREAD

**Issue by saffru** [networked-aframe/networked-aframe#157]
I've created an environment where I move with more type of device. 
If I move into it with the browser of pc the movement of the entity can be seen from other user. But, when I move with Oculus Go (or smartphone) the movement is not visibile from other user that are connected.
How can I stream the movement from all kind of device?
Below the piece of my code.
`<a-entity movement-controls="fly: true" position="0 0 0">
<a-entity id="player" networked="template:#avatar-template;attachTemplateToLocal:false;" camera="userHeight: 1.6" spawn-in-circle="radius:3" oculus-go-controls wasd-controls look-controls touch-controls>
<a-sphere class="head" visible="false" random-color></a-sphere>
</a-entity>
<a-entity oculus-go-controls="hand: right; buttonTouchedColor: #0000ff"></a-entity>
<a-entity laser-controls="hand: right"></a-entity>
 </a-entity>`

**Comment by haydenjameslee** [comment]
I assume you need to make the entity with the movement-controls the networked entity, so try putting the networked component on it.

**Comment by haydenjameslee** [comment]
To explain a bit more: the movement controls is moving the entity that has the `movement-controls="fly: true"` component on it, but networked-aframe doesn't know about that entity, so when it's position changes nothing is netowkred. The best approach is to add a networked component to both the root entity (with just a dummy template) and the camera entity (with your avatar-template).

**Comment by blasco** [comment]
the movement controls are not working since version 1.0.2 (not sure if this was the exact version, check in a frame extra issues) with the oculus go. There is an issue open in a frame extra repo, if you toll back to version 0.9 (and the corresponding a frame extra version) it should work
