### ISSUE TITLE
Client disconnects when entering VR mode on mobile device

### ISSUE THREAD

**Issue by ahomentc** [networked-aframe/networked-aframe#161]
A few seconds after my mobile device (iphone) enters VR mode, it disconnects automatically. What could be causing this? It works perfectly when not in VR mode. This error occurs with both easyrtc and wseasyrtc.

**Comment by haydenjameslee** [comment]
Are you able to get logs from the browser? Its surprising that its even happening with wseasyrtc, which is usually very stable.

**Comment by ahomentc** [comment]
Here's logs from iPhone 6s safari:
https://imgur.com/a/9lQUJPl

And this is with wseasyrtc.

**Comment by hthetiot** [comment]
Should be fixed by #175 open-easyrtc migration

**Comment by vincentfretin** [comment]
see #240
