### ISSUE TITLE
Glitch example not working

### ISSUE THREAD

**Issue by nrgapple** [networked-aframe/networked-aframe#167]
https://github.com/networked-aframe/networked-aframe/blame/master/docs/hosting-networked-aframe-on-a-server.md#L10

**Comment by haydenjameslee** [comment]
What isn't working about it?

**Comment by nrgapple** [comment]
Nevermind. It must have been my mac. It is working on windows

**Comment by haydenjameslee** [comment]
Ok thanks for closing. In the future for bug reports please give as much information as you can so we can solve the problem quickly.
