### ISSUE TITLE
Migrate to open-easyrtc

### ISSUE THREAD

**Issue by hthetiot** [networked-aframe/networked-aframe#170]
Hello,

You may want to migrate from `easyrtc` to `open-easyrtc` 2.0.x because `easyrtc` is not maintained and contain secutiry issues that will be fixed.

For more details about open-easyrtc and the changes, see here:
- https://github.com/open-easyrtc/open-easyrtc/issues/6

About security issues:
- https://github.com/priologic/easyrtc/issues/451

Note: you will need to replace NodeJs require by require('open-easytc');
Note 2: open-easyrtc use socket.io 2+

Thank you for using easyrtc in the first place.

Best Regards.

**Comment by hthetiot** [comment]
Cc @haydenjameslee easyRTC contains many security issues I do recommend you migrate to Open-easyrtc for secure your package and project.

**Comment by haydenjameslee** [comment]
@hthetiot I've been working on new version of NAF that doesn't use any third party libraries for WebRTC support. No timeframe on when I'll be finished however.

**Comment by hthetiot** [comment]
@haydenjameslee Migrating to open-easyrtc take only to change the package and `easyrtc` to `open-easyrtc` on the server side. Would you like me to make a PR. So you can release a Secure version of networked-aframe, then release your new version or signaling via a major release incremenet.

**Comment by hthetiot** [comment]
@haydenjameslee  See PR Here https://github.com/networked-aframe/networked-aframe/pull/175
With big power come big responsability, the security of your users should always come first.

**Comment by TheBricktop** [comment]
@hthetiot  how to change the easy-rtc to open rtc myself ? I might fork but currently im creating my own virtual chat so for now im only cobbling the stuff together.

**Comment by hthetiot** [comment]
See #175 long story short

> 1. npm uninstall easyrtc
> 2. npm install open-easyrtc
> 3. `require('easyrtc')` to `require('open-easyrtc')` into `server/easyrtc-server.js`

Done.

**Comment by haydenjameslee** [comment]
At some point this week I'll be removing easyrtc from the master branch completely. It's being replaced with an adapter that doesn't rely on any third party webrtc libraries: https://github.com/networked-aframe/naf-native-webrtc-adapter

**Comment by haydenjameslee** [comment]
Here's the draft PR: https://github.com/networked-aframe/networked-aframe/pull/176

Would love feedback.

**Comment by haydenjameslee** [comment]
0.7.0 has been released: https://github.com/networked-aframe/networked-aframe/releases/tag/0.7.0

**Comment by vincentfretin** [comment]
See #240
