### ISSUE TITLE
Aframe 9.2 - example with controllers doesn't works anymore

### ISSUE THREAD

**Issue by HyroVitalyProtago** [networked-aframe/networked-aframe#173]
Replace aframe version from 7.0 to 9.2 in head script, the network doesn't work anymore...
As a note, it works with aframe 8.0 ; and it seems to be linked to the fact that networked components are in a parent one.
https://github.com/networked-aframe/networked-aframe/blob/master/examples/tracked-controllers.html

**Comment by vincentfretin** [comment]
There was an issue for latest aframe version that I fixed here https://github.com/networked-aframe/networked-aframe/commit/5260154c7ed9ef43637e092bf0a443f730c6d34c
Please reopen if you still have issues with master and latest aframe 1.1.0 or 1.2.0.
