### ISSUE TITLE
Ownership change, gained, lost events no longer fire

### ISSUE THREAD

**Issue by PlumCantaloupe** [networked-aframe/networked-aframe#178]
Not sure when this started happening but on the most recent NAF update the ownership events do not fire (including on toggle-ownership example).

The issue seems stems from the comparison that happens in the component networked.js here: https://github.com/networked-aframe/networked-aframe/blob/4ee7157d5c1e52337913ee1054eac60bbfa08de5/src/components/networked.js#L167

The lastOwnerTime variable is never initialized (and so the comparison between date and -1 is always false).

The following line, that also checks for the -1, appears to fix the issue but I am not certain it is the correct approach. Perhaps lastOwnerTime needs to be initialized on network creation :)

```` javascript
if (owner && !this.isMine() && (lastOwnerTime < now || lastOwnerTime === -1)) {
````

**Comment by vincentfretin** [comment]
I just looked into this with current master. I don't see anything wrong with the code.
`this.lastOwnerTime` is initialized to -1 in init at https://github.com/networked-aframe/networked-aframe/blob/393ec7b8ffe22ff20e4b2f84fe6f32a7c23f7c06/src/components/networked.js#L186
and is set on connect here
https://github.com/networked-aframe/networked-aframe/blob/393ec7b8ffe22ff20e4b2f84fe6f32a7c23f7c06/src/components/networked.js#L269
and the condition you're referring here
https://github.com/networked-aframe/networked-aframe/blob/393ec7b8ffe22ff20e4b2f84fe6f32a7c23f7c06/src/components/networked.js#L216-L219
seems to works as attended.

```
Date.now()
1616314285921
-1 < Date.now()
true
```
so the comparison between -1 and a date is true here. There is no need for and additional `|| lastOwnerTime === -1`
At one point there was an issue with the implementation of `NAF.connection.getServerTime()` in the new socketio/webrtc adapters, you may have encountered an issue with this?
All three events are working properly, I can see the cube change the opacity between three users. See
https://github.com/networked-aframe/networked-aframe/blob/c3a12aeb59240ba586185c000d8e68ad948745da/examples/js/toggle-ownership.component.js#L28-L49

**Comment by vincentfretin** [comment]
I tested socketio, webrtc and easyrtc adapters, all three are working properly.

**Comment by PlumCantaloupe** [comment]
Ach, thank you. Sorry, I should have closed this a while ago.
