### ISSUE TITLE
polling webhost instead of sockethost

### ISSUE THREAD

**Issue by polytropoi** [networked-aframe/networked-aframe#179]
Hi - I've got a server-side scene generation setup for aframe scenes (e.g. https://servicemedia.net/webxr/pVBHeiaCI), and a separate host for socketio (https://strr.us).  When I make a connection, in addition to talking to the socketio server, it also polls the originating webhost a bunch of times, which is a problem because it's loading the server with redundant requests.  It does the same thing whether I use the socketio or webrtc adapter, and whether auto connecting or manual connection.  Is there a way to set the NAF transport to stop the polling, or preferably, to only poll the socket server, not webhost?

**Comment by haydenjameslee** [comment]
You could modify the NAF adapter you're using and change the behavior to poll any host you'd like. Here's the line that's does the polling I assume you're talking about: https://github.com/networked-aframe/networked-aframe/blob/master/src/adapters/naf-socketio-adapter.js#L192

**Comment by vincentfretin** [comment]
Any PR to make it configurable is welcome.
