### ISSUE TITLE
Use EasyRTC video?

### ISSUE THREAD

**Issue by fabiodr** [networked-aframe/networked-aframe#18]
Have you tested or found some issue also adding video in the mix?
I'm thinking about using the lib for audio+video conference with max. of 4 peers (maybe more if all peers are desktop with large bandwidth and can handle WebRTC full mesh load)

**Comment by haydenjameslee** [comment]
I haven't worked on that with NAF yet however it's definitely possible. You would also be able to stream three.js cameras to non-VR users, much like Facebook Spaces does with their messenger integration.

**Comment by haydenjameslee** [comment]
It shouldn't be too hard to integrate either. Feel free to put up a pull request!

**Comment by fabiodr** [comment]
Nice to know that it is feasible :)

I'll do some tests and if it goes fine, will be happy to send a pull request.

**Comment by gabrieljbaker** [comment]
@fabiodr would love to hear if you had any luck with this!

**Comment by rm8x** [comment]
I've got hacky video working, not close to PR so if anyone needs a basic example or something plz do ping me here or in the slack

**Comment by fabiodr** [comment]
@gabrieljbaker Sorry, it's in my roadmap yet.

@rm8x Would like to see an example :)

**Comment by vincentfretin** [comment]
I'm closing it as duplicate. Discussion continue on #211
