### ISSUE TITLE
Unsupported engine for networked-aframe@0.7.0

### ISSUE THREAD

**Issue by andronat** [networked-aframe/networked-aframe#181]
I was just following the basic installation example from [here](https://github.com/networked-aframe/networked-aframe/blob/master/docs/getting-started-local.md#install-dependencies).

```
$ cat package.json
{
  "name": "Test",
  "version": "0.0.1",
  "description": "My first multi-user virtual reality",
  "scripts": {
    "start": "node ./server/index.js"
  },
  "author": "AUTHOR",
  "dependencies": {
    "aframe": "^1.0.4",
    "networked-aframe": "^0.7.0"
  }
}
```

and I get the following warnings:
```
npm WARN notsup Unsupported engine for networked-aframe@0.7.0: wanted: {"node":">= 8.10.0","npm":"^4.0.5"} (current: {"node":"13.12.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: networked-aframe@0.7.0
```

Is this normal?

**Comment by haydenjameslee** [comment]
Thanks for pointing that out. I've made a fix on the master branch here: https://github.com/networked-aframe/networked-aframe/commit/5219d07594cc864bde0de0c91cd2878a213a5dc6

Does everything else work for you?

**Comment by andronat** [comment]
Hello @haydenjameslee and thanks for your super fast reply! Yes everything else seems to work. 

My only problem atm is that the Firebase plugin seems to be problematic: networked-aframe/naf-firebase-adapter#3. Do you accept PRs for NAF-Firebase?

**Comment by haydenjameslee** [comment]
Certainly accepting PRs. Haven't tested firebase for a while so it wouldn't surprise me if there's errors there.
