### ISSUE TITLE
Versions problem

### ISSUE THREAD

**Issue by chumakov-azoft** [networked-aframe/networked-aframe#183]
this url https://unpkg.com/networked-aframe/dist/networked-aframe.min.js returns https://unpkg.com/networked-aframe@0.7.0/dist/networked-aframe.min.js (seems like 0.7 version), but this doesn't contain "native-webrtc" and contains "0.6.1" string

**Comment by haydenjameslee** [comment]
Interesting! Thanks for the report, I'll have a look tonight.

**Comment by haydenjameslee** [comment]
Sorry for the delay here. I looked into this and turns out I forgot to change the version number with the 0.7.0 release, but what you are seeing at that link is indeed the 0.7.0 code. And it doesn't contain `native-webrtc` because before releasing 0.7.0 i renamed that adapter to just `webrtc`.

**Comment by vincentfretin** [comment]
There was a 0.7.1 release that fixed it apparently.
https://unpkg.com/networked-aframe@0.7.1/dist/networked-aframe.min.js
