### ISSUE TITLE
User account by mysql instead of randomly generated by server?

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [networked-aframe/networked-aframe#186]
Hello I was wondering if it is possible to do a user login by mysql instead of the server randomly generated when entering? Has anyone been working on this?

Joseph

**Comment by haydenjameslee** [comment]
Totally possible to do. You could combine a system like [this](https://medium.com/technoetics/handling-user-login-and-registration-using-nodejs-and-mysql-81b146e37419) with the existing NAF server.

**Comment by Therealjosephchrzempiec** [comment]
Hello I already have a local MySQL server that is on the same system as the networked-aframe. My problem is I do not know how in the aframe to set it up instead of using the automatic user create to have a MySQL login.

**Comment by haydenjameslee** [comment]
You'd have to change the client to handle the authentication flow, like entering the username and password, and then update [this](https://github.com/networked-aframe/networked-aframe/blob/master/server/index.js) file to do the back end work.

**Comment by Therealjosephchrzempiec** [comment]
Hello where do i change the client  part at?

**Comment by Therealjosephchrzempiec** [comment]
I have been trying and trying to figure this out this is way beyond me and what i can do. I have no clue.

**Comment by vincentfretin** [comment]
Hi @Therealjosephchrzempiec I'm sorry we can't help you further, this is far out of the scope of networked-aframe maintenance.
You need to develop your own adapter and nodejs server for this.
I'll give you some pointers though.
For the easyrtc adapter, the `clientId` comes from the easyrtc lib when you connect
https://github.com/networked-aframe/naf-easyrtc-adapter/blob/eee713b2acccd6385434a1e2a301d10ec68f4eeb/src/index.js#L99-L106 You may look at open-easyrtc library to see if this is somewhat customizable before you call connect.

Then `NAF.clientId` is set with this `clientId` in the `connectSuccess` callback
https://github.com/networked-aframe/networked-aframe/blob/6b053a345ba2a81ecda8668f596daa57519a33e7/src/NetworkConnection.js#L72

For the janus adapter, there exists a `setClientId` function on the adapter to set an id yourself before connecting.
So all this depend on the adapter and server you want to work with.

**Comment by hthetiot** [comment]
@Therealjosephchrzempiec you need to customize your easyrtc-server.js.js, the right place for an issue like that would be https://github.com/open-easyrtc/open-easyrtc
