### ISSUE TITLE
 I don't get rotation of the avatar because of the physical

### ISSUE THREAD

**Issue by deskmath** [networked-aframe/networked-aframe#189]
greetings, with the networker a-frame project I am forced to put 
entity...
          id = "player"
          networked = "template: # avatar-template; attachTemplateToLocal: false;"
          spawn-in-circle = "radius: 6;"
          kinematic-body
          look-controls
          movement-controls
          position = "0 0.3 0"
       
entity..  id = "cam" camera position = "0 0.4 -0.2"> 
 

to use the physical collisions but that restricts me to be able to obtain the rotation of the avatars, what solution can I use? I have tried everything without success.

**Comment by vincentfretin** [comment]
See https://github.com/networked-aframe/networked-aframe/issues/193 please provide an updated glitch example with your issue. Thanks.
