### ISSUE TITLE
Let application share/stream video to other peers

### ISSUE THREAD

**Issue by djoksimo** [networked-aframe/networked-aframe#190]
Hi 👋 ,

Firstly, I just wanted to say that `networked-aframe` is really cool! 😄 

I've scoured through the NAF documentation, PRs and issues, but I'm having trouble setting up video sharing/streaming via the `webRTC` adapter.

I found this Issue https://github.com/networked-aframe/networked-aframe/issues/57 (for EasyWebRTC, which is deprecated) and I found this line of code: https://github.com/networked-aframe/networked-aframe/blob/4c4c1e4f790e68ce0ceab4bbc575c596aebb1a00/src/adapters/naf-webrtc-adapter.js#L316 which says `WebrtcAdapter does not support video yet."`.

Is video chat possible with the NAF `webrtc` adapter (or some other alternative)?

I have the following template:

```html
        <template id="video-template">
          <a-entity class="webcam-entity">
            <video class="vid" id="webcam" playsinline></video>
            <a-entity
              geometry="primitive: circle; radius: 3"
              class="vid-entity"
              random-position
              rotation="0 45 0"
              shadow
              material="src: #webcam"
            ></a-entity>
          </a-entity>
        </template>

...

      <a-entity networked="template:#video-template"></a-entity>

```

**Comment by haydenjameslee** [comment]
Its not supported yet but its certainly possible. The Mozilla Hubs team have implemented WebRTC video into their fork of networked-aframe so there's the existence proof. I'm not aware of any adapters aside from their's that has implemented it however, and i'm not sure how easy their's would be to use. It wouldn't be too hard to add it to the webrtc adapter yourself however, just following a simple tutorial like this: https://www.scaledrone.com/blog/webrtc-tutorial-simple-video-chat/

**Comment by kylebakerio** [comment]
I had the same issue and came up with a (currently crude) example: https://github.com/kylebakerio/networked-aframe

**Comment by hthetiot** [comment]
@djoksimo Need need to wait next April to me done, here is the PR https://github.com/networked-aframe/networked-aframe/pull/261
