### ISSUE TITLE
Offline mode?

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [networked-aframe/networked-aframe#191]
Hello i was trying the entworked-aframe offline just local network only and it seems i can't Looking at it closely there are some parts where it requires it to be online. Is there a way to do it offline just incase my internet doesn't work? I still would love to play on this when and if my network goes out.

Joseph

**Comment by haydenjameslee** [comment]
Make sure you're hosting all the files referenced by <script> tags locally rather than hosting on the internet. You can indeed do what you're trying to achieve if you do that. Which parts did you find that require being online?

**Comment by Therealjosephchrzempiec** [comment]
Hello sometimes my internet goes offline and i can not enter the networked-aframe. Shows up as blank. I see the npm and running not sure about the nodejs and aframe part.


Joseph

**Comment by haydenjameslee** [comment]
In your index.html file are you referencing any files that aren't hosted locally in script tags?

**Comment by Therealjosephchrzempiec** [comment]
Hello yes it is the basic.html file... It looks like theserver is working offline i can render a basic html file. But not the basic.html file.


Joseph

**Comment by haydenjameslee** [comment]
Right, I mean within that basic.html file are there any references to script files that are not hosted locally?

**Comment by Therealjosephchrzempiec** [comment]
Yes sorry i believe they are the ones.

**Comment by vincentfretin** [comment]
This has been answered. Make sure you don't use any external urls in the script tags.

**Comment by Utopiah** [comment]
Suggested doc add via https://github.com/networked-aframe/networked-aframe/pull/406
