### ISSUE TITLE
Connecting to server from a different domain

### ISSUE THREAD

**Issue by Sliferblade** [networked-aframe/networked-aframe#192]
Is it possible to host the node.js server via AWS and connect to it through client code distributed from a separate server/domain or platform such as electron? I presume one of the issues will be CORS?
Thanks!

**Comment by Sliferblade** [comment]
Managed to get it working after finding the 'serverURL' parameter within 'networked-scene' and setting it to the AWS URL. I have yet to test it on electron but I assume it works fine.

**Comment by haydenjameslee** [comment]
Yup WebSockets don't have CORS by default which makes applications like this pretty easy. Glad you got it working.

https://www.freecodecamp.org/news/how-to-secure-your-websocket-connections-d0be0996c556/
