### ISSUE TITLE
 Problems integrating aframe-extras, to obtain collisions and player rotation. (nav-mesh or static-body).

### ISSUE THREAD

**Issue by deskmath** [networked-aframe/networked-aframe#193]
I am trying to integrate physics in my project, the best option is using nav-mesh but when integrating "movement-controls =" constrainToNavMesh: true "in the player it gives error:
aframe-extras.min.js: 1 Uncaught TypeError: Cannot read property 'object3D' of null
    at i. <anonymous> (aframe-extras.min.js: 1)
    at i. <anonymous> (aframe-extras.min.js: 1)
    at HTMLElement.tick (a-scene.js: 709)
    at HTMLElement.render (a-scene.js: 759)
    at bind.js: 12
    at f (three.js: 24686)
    at e (three.js: 15038)

The first option was to integrate static-body but I had to remove the camera from the player and lost the possibility of seeing the player rotate.

Is it possible to integrate aframe-extras within the player? and be able to use physics and have the position and rotation of the player?

**Comment by haydenjameslee** [comment]
I'm not very familiar with aframe-extras unfortunately.

It might help other folks answer this issue if you make a glitch.com example project.

**Comment by deskmath** [comment]
Hi Hayden , 
I share a simple project with nav mesh aframe-extras and networker in git, the intention is to be able to integrate the rotation into the avatar without error.

https://github.com/deskmath/NavmeshRotationavatar

https://glitch.com/edit/#!/caseta?path=public%2FferiaAvatar01.html%3A1%3A0

thanks and great work.

**Comment by djoksimo** [comment]
I'm experiencing the same rotation-tracking issue with a-frame extras.

I'm currently looking into a potential solution.

**Comment by matroskin87** [comment]
I was able to successfully integrate physical system only with older versions of the a-frame. A-Frame version 0.7.0 and aframe-extras version 3.13.1

**Comment by kylebakerio** [comment]
I do know there were breaking changes in how the camera was handled (in regards to rotation) in Aframe 0.8. That may be related.

**Comment by vincentfretin** [comment]
This discussion is quite old now and the glitch you shared @deskmath doesn't exist anymore. 
Do you have a cameraRig, an entity that is the parent of the camera? This is really needed I think.
Can somebody create a glitch with aframe 1.1.0 and latest aframe-extras and physics (I know aframe-extras has issues with latest threejs included in aframe 1.2.0) with cannon or ammo backend?
Hubs is doing it so there is definitely no issue in networked-aframe. :D

**Comment by kylebakerio** [comment]
I use aframe-extras and physics in mine. Unfortunately, A-Frame itself uses a version of THREE that breaks all the physics libraries, but it tentatively worked for me, though I haven't deeply tested this yet. I also wasn't yet using anything to constrain to nav mesh.

However, that in itself shouldn't cause a problem, I think.

I would like to build up an NAF demo that has physics with it as a kind of 'multi-user A-Frame starter kit' down the road.

**Comment by vincentfretin** [comment]
If you didn't see it, I started an example with the ammo driver #270 any contributions are welcome.

**Comment by beckchan1** [comment]
It seems that I am also facing similar issue when combine the navmesh to networked aframe. Please see the code below. When I remove the wasd-controls, the navmesh is work fine but other people cannot see my avatar is moving on the same networked aframe room. If I add the wasd-controls, the navmesh will be no longer work but my avatar can move normally. Could anyone has any suggestions? Thanks a lot!
 
<a-entity id="rig" movement-controls="constrainToNavMesh:true;" position="0 0 0">
	<a-entity id="player" camera position="0 2.6 0" wasd-controls look-controls networked="template:#avatar-template;attachTemplateToLocal:false;">
	</a-entity>
</a-entity>

**Comment by vincentfretin** [comment]
I didn't do any project that uses navmesh with aframe-extras movement-controls component, so I can't help with this.
Do you have an error in the console? Maybe aframe-extras current released version is not compatible with aframe 1.3.0? Did you try the master branch https://github.com/n5ro/aframe-extras ?
Does someone that use it have feedback on this?

You may be interested in Ada's simple-navmesh-constraint component as an alternative to aframe-extras movement-controls.
https://github.com/AdaRoseCannon/aframe-xr-boilerplate
