### ISSUE TITLE
Changing scenes?

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [networked-aframe/networked-aframe#195]
Hello i wondering how can i change scenes. I have found the forest one but got lost trying to change it from the current one in the basic.html with the multi users to the forest one with the multi users. from networked-aframe.

in the forest scene it has 

`  <a-scene environment="preset: forest"> `

and in the networked-aframe one it has

` <a-scene networked-scene="
      room: dev;
      debug: true;
      adapter: socketio;
    ">
      <a-assets>`

i copied all the js files it needs to make it run. And i have changed the sense to this 

` <a-scene environment="preset: forest;
      room: dev;
      debug: true;
      adapter: socketio;
    ">
      <a-assets>`

But my lack of coding skills are not all here yet. Can someone please help me to fix this so i can make this work?

Joseph

**Comment by silverslade** [comment]
Hi Joseph!
Try these steps:

1. open the basic.html source and add
 `<script src="https://unpkg.com/aframe-environment-component@1.1.0/dist/aframe-environment-component.min.js"></script>` 
inside the "head" tag
2. add `<a-entity environment="preset: contact; fog: 0"></a-entity>`
inside the "a-scene" tag

Maybe there is a problem about the "fog" parameter (so you have to set it to 0).

Alessandro

**Comment by Therealjosephchrzempiec** [comment]
Hello i see something new now but it;s mostly washed out. [http://deletethis.info/newscene-washedout.png](url)

**Comment by silverslade** [comment]
> > > Hello i see something new now but it;s mostly washed out. [http://deletethis.info/newscene-washedout.png](url)

So it's fine.
Other presets: none, default, contact, egypt, checkerboard, forest, goaland, yavapai, goldmine, threetowers, poison, arches, tron, japan, dream, volcano, starry, osiris

Reference [https://github.com/supermedium/aframe-environment-component](url)

**Comment by Therealjosephchrzempiec** [comment]
Hello Ever sense i loads from tron to japan to the forest is all washed out in colors. I have looked at the other demo forst one and the colors are great but not here for some odd reason. however the scene does load.

**Comment by silverslade** [comment]
> 
> 
> Hello Ever sense i loads from tron to japan to the forest is all washed out in colors. I have looked at the other demo forst one and the colors are great but not here for some odd reason. however the scene does load.

I think you could remove lights and other entities from the basic.html file. Try to leave only the environment entity (remove sky, light, and particles).

**Comment by Therealjosephchrzempiec** [comment]
Hello i did remove all that and the colors are great now like the other demo. However everything is Dim like it is night time. I did search online and it seems i need a Sky of some kind so i found online a hex colors for the sky and that seem to brighten up everything like day time. Thank you so much for the help.

**Comment by silverslade** [comment]
:-)
I think this issue can be set as closed, good luck!

**Comment by Therealjosephchrzempiec** [comment]
> :-)
> I think this issue can be set as closed, good luck!

Hello it is still there under User account by mysql instead of randomly generated by server?

**Comment by Therealjosephchrzempiec** [comment]
Hello yes thank you.
