### ISSUE TITLE
collision with scene?

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [networked-aframe/networked-aframe#197]
Hello I'm trying out the forest scene with a lot of trees. But the problem is I'm walking through the trees. It is possible to stop that top walking through things like that?

Joseph

**Comment by haydenjameslee** [comment]
Take a look at using a physics system like this: https://github.com/donmccurdy/aframe-physics-system

**Comment by haydenjameslee** [comment]
Given that this is not related to Networked-Aframe and is just a regular A-Frame question you may find better help looking in the A-Frame documentation and support forums: https://aframe.io/community/

Networked-Aframe is only responsible for the multi-user layer, A-Frame is the layer underneath that is responsible for tying everything together (like physics for example)

**Comment by Therealjosephchrzempiec** [comment]
Thank you Hayden
