### ISSUE TITLE
Better handling when microphone isn't authorized for webrtc

### ISSUE THREAD

**Issue by wolfgangmeyers** [networked-aframe/networked-aframe#198]
I'm seeing a problem where the networked component doesn't function properly when audio is enabled but a user doesn't authorize use of their microphone. It happes on line 369 of naf-webrtc-adapter:

https://github.com/networked-aframe/networked-aframe/blob/4c4c1e4f790e68ce0ceab4bbc575c596aebb1a00/src/adapters/naf-webrtc-adapter.js#L369

If the site isn't given permission to use the microphone, the promise is rejected. I see two problems with the current handling:

First, the details of the exception aren't printed out. I had to capture it in a debugger to see that it was a "permission denied" error. Currently it just prints out "DOMException" with no other details.

Second, when this error is caught, it prevents the client from sending any data at all, although the client still receives data from other peers. If a user doesn't authorize the site to use their microphone, ideally they would still be able to participate as if on permanent mute.

**Comment by haydenjameslee** [comment]
Good suggestion and thanks for pointing out there's not a proper error log. Will look into this.

**Comment by wolfgangmeyers** [comment]
FYI this was from testing on a Magic Leap 1 device with the Helio browser.

**Comment by haydenjameslee** [comment]
Merged #201

**Comment by wolfgangmeyers** [comment]
I didn't fix the error message, but seems like a minor issue, maybe not worth reopening.
