### ISSUE TITLE
washed out avatars in world.

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [networked-aframe/networked-aframe#199]
Hello i have changed the scene in the basic.html everything looks great but the avatars are all white. I didn't take out the avatar color random-color that is still there its just all white avatars. I try to put back the original scene and all avatars look good. Not sure why. I'm seeing this in all computers in the networked had anyone came across this before. sense it does have to do with being in the socket.io part of the avatar seeing it.

Joseph

**Comment by kylebakerio** [comment]
You would need to make a glitch.com example to demonstrate. Sounds like user error.

**Comment by vincentfretin** [comment]
Hi, there is nothing we can do here without a reproducible example. Please create a glitch to reproduce the problem and come visit us on #networked-aframe channel on A-Frame slack, though I don't think your issue is specific to networked-aframe here.
