### ISSUE TITLE
WebRtcPeer.channel.onerror gets invoked when a user exits the site

### ISSUE THREAD

**Issue by djoksimo** [networked-aframe/networked-aframe#204]
In the `basic-audio.html` example with `audio: true` and `adapter: webrtc`:

When a user leaves a room (closes the tab) with more than 1 active user (after accepting microphone permissions):

An error message is logged from the `WebRtcPeer.channel.onerror` handler:

![image](https://user-images.githubusercontent.com/32694765/82616280-c58f6780-9b9a-11ea-9adf-a5d336f0ef19.png)

after adding a regular `console.log` with the error expanded, I see:

![image](https://user-images.githubusercontent.com/32694765/82616447-32a2fd00-9b9b-11ea-9384-cb0cae3b1bd5.png)

**trace**:

![image](https://user-images.githubusercontent.com/32694765/82616598-af35db80-9b9b-11ea-9685-b5c83ef63d66.png)

**Comment by vincentfretin** [comment]
see #240
