### ISSUE TITLE
Displaying the generated name of the user within the html page?

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [networked-aframe/networked-aframe#205]
Hello i can see in the command line the username that is Generated when the user enters. Is it possible to display that username above the avatar it's self becuase i can not tell who is who in there?

Joseph

**Comment by Therealjosephchrzempiec** [comment]
I think i found what I'm looking for. In looking through the code i found this..

socket.on("connect", () => {
        NAF.log.write("User connected", socket.id);
        self.myId = socket.id;
        self.joinRoom();
      });

I'm not sure if this is correct in figuring out how to post that generated username above the avatar. If someone can help me out and point me in the right direction because this is a driving me a little crazy.

**Comment by Therealjosephchrzempiec** [comment]
Hello i know it has something to do with the clientid. Im seeing a lot of that now. I need to know how to display the user that is generated above each avatar.

**Comment by haydenjameslee** [comment]
Here's an example that shows a user's name above the avatar's head: https://glitch.com/edit/#!/naf-nametags?path=public%2Findex.html%3A1%3A0

**Comment by Therealjosephchrzempiec** [comment]
Thank you Hayden very much.  I have been searching and searching Got lost many times.

**Comment by haydenjameslee** [comment]
I just updated that demo to work with the latest version of Networked-Aframe too, so if it didn't work a few minutes ago try again now.

**Comment by Therealjosephchrzempiec** [comment]
There looks like some kind of erro. It asked me for a username and that is great. However when entering the basic page it shows the pair of eyes from the user. And also I can not see other avatars if i open a different browser like firefox.

**Comment by Therealjosephchrzempiec** [comment]
I have just tried the demo 2 minutes ago and i don't see the change of code. It still looks the same. However that other demo from glitch has some errors on it. Well not error more like the camera view is wrong. I can only see my own eye from the avatar that is all.
![glitch](https://user-images.githubusercontent.com/50338148/83370433-66490880-a38d-11ea-8d1f-59099d80e61d.png)

**Comment by Therealjosephchrzempiec** [comment]
Hello Hayden thank you for the nametag one. But i was wondering if there was a way of display that generated name that the server has created on the server backend to be displayed? The reason why I'm asking is because in your shooter demo I'm working on a game and to keep track of how many times the person get hit it will save to a database. The probem is the avatar already has a name generated by the server So if i use the nametag one to store the points it doesn't know what avatar it really came from.

**Comment by haydenjameslee** [comment]
After you have connected to the room (which you can detect via the `onConnect` callback in networked-scene), you can get the socket ID via `NAF.clientId`. If you wanted to display that ID in the nametag you would call this line again: https://glitch.com/edit/#!/naf-nametags?path=public%2Findex.html%3A119%3A52 but with `username` replaced by `NAF.clientId`.

As far as the naf-nametag example goes, you need to move the player away from the starting position so you can see the other players in the room, since they all load on top of each other.
![image](https://user-images.githubusercontent.com/4357996/83429371-f45ed680-a401-11ea-84cf-654b70ad8b6f.png)

**Comment by Therealjosephchrzempiec** [comment]
Hello hayden thank you. As far as the avatar goes. This is the demo from that link you gave me in here. So that demo is off a little with the avatars and position.

**Comment by vincentfretin** [comment]
For the eyes I think I answered in #230 
I think all have been answered here. I close.
