### ISSUE TITLE
Error with naf-nametags

### ISSUE THREAD

**Issue by epic-developer** [networked-aframe/networked-aframe#207]
Running [naf-nametags.glitch.me](https://naf-nametags.glitch.me/) results in the following error in the console:
Uncaught TypeError: Cannot read property 'setAttribute' of null
    at HTMLElement.onSceneLoad ((index):41)
    at Object.module.exports.fireEvent (index.js:120)
    at HTMLElement.value (a-node.js:228)
    at a-node.js:118

**Comment by haydenjameslee** [comment]
The naf-nametags demo was on an old version of NAF. I've updated it now: https://glitch.com/edit/#!/naf-nametags
