### ISSUE TITLE
New camera Position move within same sense for networked users

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [networked-aframe/networked-aframe#210]
Hello So far I'm loving the networked aframe. But i have a small problem I'm not sure if anyone an help me. So my problem is I created a box image in the sense with a link in it `<a-link href="basic.html" position="-3.5 1.5 -1.0"></a-link>` I'm using the teleporter code i have fround online. What I'm trying to do is move to another position location within the same sense without having to refresh the whole page of the basic.html for other users. Is there a way on doing that so when other come it they don't have to keep clicking on the box and having the whole page fresh?

Joseph

**Comment by haydenjameslee** [comment]
It sounds like what you want is a regular box with a collider on it, and when you click on the box you run some code to move the player to a new position. A-link may not be the right tool here (although I'm not super familiar with A-link myself)

**Comment by Therealjosephchrzempiec** [comment]
Hello Hayden thank you for the response back. When a player enters enters a sense they start at a position within a sense. Basically the same thing when click on the box the player can move to that position without having to move/walk to that location within the sense or reloading the webpage.


Joseph

**Comment by vincentfretin** [comment]
So do you have a teleport working when clicking on a box?
I'm not sure I followed what you want to achieve here. You want other participants that connect to teleport to the same place of the current user in the room? Is that it? You will need some specific code for this, probably a hidden networked persistent entity (see #238) where a custom component where the latest participant that clicked on a box save their position in this component data, synchronize this with a networked schema, and an update function in this component that teleport everyone at the same place. This is how I would write it.
