### ISSUE TITLE
this is you being bugged to update the readme or write elsewhere more about adapters and architecture. :)

### ISSUE THREAD

**Issue by kylebakerio** [networked-aframe/networked-aframe#212]
looking forward to reading what you write. Thanks!

**Comment by MignonBelongie** [comment]
Me too.

**Comment by vincentfretin** [comment]
What information are you interested in exactly? Can you give more details?

**Comment by kylebakerio** [comment]
This was something I commented when I first read the documentation. In the readme, it was specifically mentioned that we should ask for more information if we wanted the docs to be updated on this topic. So I asked. I wasn't sure what he had in mind to share.
