### ISSUE TITLE
How to stop two basic.html pages interacting with each other?

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [networked-aframe/networked-aframe#214]
Hello I'm having a little problem maybe someone can help me out i would like to have to of the basic.html pages like basic.html and basic2.html to run different scenes the problem is When i go into the first baisc.html page i can see the avatar from the basic2.html. Is there possible way to not have them interact with each other?

Joseph

**Comment by haydenjameslee** [comment]
You can set the room property of networked-scene to be different in each file. See: https://github.com/networked-aframe/networked-aframe#scene-component

For example:

`<a-scene networked-scene="room: room-one">`

`<a-scene networked-scene="room: room-two">`

**Comment by Therealjosephchrzempiec** [comment]
Hello Hayden Thank you. That did work.
