### ISSUE TITLE
Basic example, Cannot connect to socket.io, getting 404 on socket.io/?EIO=3&transport=polling&t=NB-Y-KC

### ISSUE THREAD

**Issue by github-user-77** [networked-aframe/networked-aframe#218]
Hi There,
Total NAF and Node noob here. I've set up the NAF tutorial on my server and the NAF server runs okay, but the basic example gives a lot of 404 errors for http://mydomain.com/socket.io/?EIO=3&transport=polling&t=NB-Y-KC  (that's one, all the other 404 errors have different bunches of letters in place of NB-Y-KC), and the basic example doesn't work at all, as in, there are no avatars logged in, just a nice grid in empty space :)

I can't figure out how to fix this – is it something to do with the way I have set up the server (apache2 on Ubuntu 20), perhaps the ProxyPass?

I've really tried searching for solutions, but my ignorance of Node (I think) makes it very difficult to know what to do. Any help most appreciated!

B-30

**Comment by vincentfretin** [comment]
Hi, you can come to the #networked-aframe channel on A-Frame slack if you want some help, nice folks to help there.
