### ISSUE TITLE
onConnect does not seem to work

### ISSUE THREAD

**Issue by kylebakerio** [networked-aframe/networked-aframe#220]
I'm passing a resolve() to a promise to onConnect, so I can get a .then() after connection.

It never gets called. I can console.log the options I'm passing, with the function, and call it manually, and all the lights turn on that I was waiting for.

_sidenote: would prefer to subscribe to an event_

**Comment by QuinnCiccoretti** [comment]
Can the 'connected' event be used for this? It's used in the `basic-events` example, but is conspicuously absent from the Readme.

https://github.com/networked-aframe/networked-aframe/blob/130687dc49859c8baf8de61176fbbb4249405ee9/examples/basic-events.html#L129

It seems like 'connected' almost fires before onConnect. `NAF.connection.getConnectedClients()` always returns an empty object when I listen to the 'connected' event.

**Comment by vincentfretin** [comment]
You can indeed use the "connected" event or onConnect with a callback like this
```
NAF.connection.onConnect(() => {                                              
  // do something
});
```

Note that `onConnect` doesn't return a Promise in the easyrtc adapter. But it does for the janus adapter and is called when all RTCPeerConnection to other participants are created.

**Comment by vincentfretin** [comment]
If you use `networked-scene="connectOnLoad: false"` and doing `scene.components["networked-scene"].connect()` yourself, please note that for the janus adapter, `scene.components["networked-scene"].connect()` returns a Promise, it's called when all RTCPeerConnection to the other participants are created. This is not the case for the other adapters like easyrtc.
```
scene.components["networked-scene"].connect().then(() => { // do something });
```
