### ISSUE TITLE
Live-streaming Volumetric Video Avatars in WebXR

### ISSUE THREAD

**Issue by Philipvn** [networked-aframe/networked-aframe#221]
We, E-spaces, have a returning client —read: they have money— asking us to develop —completely from scratch if need be— a general-purpose metaverse/cyberspace system that is WebXR based and where all the avatars are (can be) live-streamed volumetric video. The volumetric video streams come from depth-cameras on flagship smartphones such as Apple iPhones and Samsung Galaxy Notes, as well as tablets such as the latest Apple iPad Pro which sports a LiDAR camera on its back.

I am posting here to find the following two things that we are presently looking for:

- Devs w. experience in displaying and/or live-streaming RGD-D into M.U. WebXR spaces.
- Devs w. experience in back-end server SW for M.U. WebXR spaces that are dynamically scalable in terms of number of synchronous avatars inside a single space.
- Existing open-source codebases directly relevant to the things described above that we should consider so as to get off to a running start on this project.

Yes, this project will give back to the open-source community as much as we can push our paying client to contribute. 

At your discretion please respond publicly here or privately to pvn@e-spaces.com

Thank you!

**Comment by vincentfretin** [comment]
You may want to add a job description on the #jobs channel in A-Frame slack https://aframe.io/slack-invite/ if you didn't do it and if it's still something you want to do.

**Comment by vincentfretin** [comment]
I know https://www.8thwall.com is supporting some hologram (is that the same thing?), if someone is interested by this topic:
https://medium.com/8th-wall/new-integration-microsofts-mixed-reality-capture-studios-brings-lifelike-holograms-to-the-web-d1d7e70d3d77 and https://www.8thwall.com/8thwall/mrcs-aframe

https://www.8thwall.com/blog/post/41172588204/how-to-create-a-webar-hologram-project-using-depthkit-cinema

**Comment by kenchikuliu** [comment]
> 
> 
> I know https://www.8thwall.com is supporting some hologram (is that the same thing?), if someone is interested by this topic:
> https://medium.com/8th-wall/new-integration-microsofts-mixed-reality-capture-studios-brings-lifelike-holograms-to-the-web-d1d7e70d3d77 and https://www.8thwall.com/8thwall/mrcs-aframe
> 
> https://www.8thwall.com/blog/post/41172588204/how-to-create-a-webar-hologram-project-using-depthkit-cinema

Thx, Is there any other solution except 8thwall?
