### ISSUE TITLE
How to Host My Virtual Space in my online Web-site - Multi-User

### ISSUE THREAD

**Issue by tiagomachado96** [networked-aframe/networked-aframe#225]
I cant understand how to connect my project to my online server.
I'm new at programing and I really like this whole Virtual thing.
I'm a 3D artist and i want to launch my own Virtual Exposition Room, where people can interact with eachother.
But I can't find the right way to do it.

I tried to follow everything but it's so confusing.

Please help me!!!

**Comment by github-user-77** [comment]
@tiagomachado96, to run NAF online, you'll need to set up a server and deploy NAF to it.

If you're not familiar with doing that, and you want a multi-user space where people can interact with each other and see your 3D art, you might want to check out Mozilla Hubs. It uses NAF underneath, but it is easy to create your own space, just click a couple of buttons and you're away. You can bring in your own 3D models etc and/or build a customised 3D space using the Hubs built-in tools. It's a good way to start, then as you learn more you might want to look at creating your own server using NAF.

https://hubs.mozilla.com

and check out the docs at:
https://hubs.mozilla.com/docs/welcome.html
