### ISSUE TITLE
Camera view

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [networked-aframe/networked-aframe#230]
Hello i was on glitch trying out the naf-nametags on https://glitch.com/~naf-nametags Everything looks good. But i came across one small problem the camera view. It looks like i can see behind the eyes but the eyes are pointed out more. How can i fix this problem? 

Joseph

**Comment by msitarzewski** [comment]
`<a-entity id="player"
        networked="template:#avatar-template;attachTemplateToLocal:false;"
        camera
        position="0 1.6 0"
        spawn-in-circle="radius:3"
        wasd-controls look-controls
        >
        <a-sphere class="head"
          **visible="false"**
          random-color
        ></a-sphere>
      </a-entity>`

**Comment by vincentfretin** [comment]
Don't show the avatar for yourself in this case, set attachTemplateToLocal to false.
```
networked="template:#avatar-template;attachTemplateToLocal:false;
```
