### ISSUE TITLE
Multiple people operate one object？

### ISSUE THREAD

**Issue by ruliusuifeng** [networked-aframe/networked-aframe#232]
I tried to combine the physics module, but when two people play together, each will generate a set of physical objects. Each can only play their own physical objects. 
Is there a demo that allows multiple people to operate one object? I will take it away and you will take it back.

**Comment by vincentfretin** [comment]
You should come to the #networked-aframe channel on A-Frame Slack https://aframe.io/slack-invite/ to read the comments of the previous months and pinned comments there. I answered several times this topic (takeOwnership and persistent). I don't have an running example to give you, only some snippets available on the channel.

**Comment by ruliusuifeng** [comment]
> You should come to the #networked-aframe channel on A-Frame Slack https://aframe.io/slack-invite/ to read the comments of the previous months and pinned comments there. I answered several times this topic (takeOwnership and persistent). I don't have an running example to give you, only some snippets available on the channel.

Hello, I saw your example on slack, but I don’t know how to add it to my demo. Can you provide me with a working demo? Is static-media an existing template id? How does someHandler work? I tried to add to the networked init method, only one ball remained, but the changes of the ball were invisible to each other.

**Comment by vincentfretin** [comment]
See the full second pinned thread https://app.slack.com/client/T0FAGUM6W/C65MC3NSF/thread/C65MC3NSF-1607705738.106800
There is a glitch https://glitch.com/edit/#!/nafsoundardemoroom-vincent with a sphere that is persistent that use a random color on a sphere by doing the takeOwnership only for the first user.

**Comment by vincentfretin** [comment]
see #238 as well
