### ISSUE TITLE
hand-controls

### ISSUE THREAD

**Issue by ruliusuifeng** [networked-aframe/networked-aframe#233]
Hello.
When I synchronized the model of the hand, in my perspective, I manually moved other people's hands along with it.
 I want us to wave our hands differently, for example, let the other person see me compare Thumbs up

**Comment by vincentfretin** [comment]
Sorry I don't fully understand what you are saying. I don't know if you have an issue or want an enhancement.
Does the examples/tracked-controls.html works for you? What are you trying to achieve compared to this example? Can you share an example on glitch.com?
Ross here
https://aframevr.slack.com/archives/C65MC3NSF/p1613982391032200?thread_ts=1613920593.023200&cid=C65MC3NSF
wanted something like synchronized basic hand gesture when detecting the different pressed buttons like grip gesture, this is what you are referring with Thumbs up?

**Comment by kylebakerio** [comment]
@vincentfretin I also wanted this feature so today decided to hack it out. I did 98% of the work, just have some little clean up tweaks to make: https://nctl2.glitch.me/tracked-controllers.html

Feel free to test it and let me know what you think, I'll make a pull request soon.

**Comment by vincentfretin** [comment]
Great, I need to test that!

**Comment by vincentfretin** [comment]
#355 is addressing it.
