### ISSUE TITLE
Configure Github Actions

### ISSUE THREAD

**Issue by vincentfretin** [networked-aframe/networked-aframe#237]
I removed travis in https://github.com/networked-aframe/networked-aframe/commit/16264efba6f5314cffd35cf3af15f39d371dcb05 because travis.org is shutting down.
We should move the testing to Github Actions. If anyone know how to run the tests with Github Actions, I'll gladly accept a PR.

**Comment by suresh-borad** [comment]
@vincentfretin I can help with this. 
I have tried testing commands in my local but getting some dependencies errors.
Tried command: 
```
npm test
npm run test:firefox
npm run test:chrome
```
Error Log:
<img width="709" alt="Screenshot 2021-05-06 at 8 24 11 PM" src="https://user-images.githubusercontent.com/40260338/117319553-0914db80-aea9-11eb-8cb1-584d4defc27c.png">

```
$ karma start ./tests/unit/karma.conf.js
06 05 2021 20:23:29.326:ERROR [plugin]: Cannot find plugin "karma-browserify".
  Did you forget to install it?
  npm install karma-browserify --save-dev
06 05 2021 20:23:29.338:ERROR [preprocess]: Can not load "coverage", it is not registered!
  Perhaps you are missing some plugin?
06 05 2021 20:23:29.338:ERROR [preprocess]: Can not load "browserify", it is not registered!
  Perhaps you are missing some plugin?
06 05 2021 20:23:29.338:ERROR [preprocess]: Can not load "env", it is not registered!
```

Node: v12.18.0
npm: 6.14.4
yarn: 1.22.10

NOTE: I've tried with yarn but same error.

**Comment by vincentfretin** [comment]
Oups, I deleted all browserify related packages in #259 without running the tests. :(
You can try reintroducing some of the needed packages I removed.

**Comment by vincentfretin** [comment]
Or maybe karma can work with webpack instead of browserify? I don't know.

**Comment by suresh-borad** [comment]
I will try first with webpack if not work then try with older packages

**Comment by vincentfretin** [comment]
You can create a PR without necessary attaching it to an issue, so we can first fix running the tests, then you can work on github actions integration. Or you may do both in the same PR, as you wish. I'm just glad you're working on it. ;-)

**Comment by suresh-borad** [comment]
@vincentfretin You can review the above PR. I have committed all changes in the same PR.
