### ISSUE TITLE
Add an example of a shared sphere

### ISSUE THREAD

**Issue by vincentfretin** [networked-aframe/networked-aframe#238]
Add an example in the repo of a shared sphere where each participant can click on it to change its color.
see discussion https://aframevr.slack.com/archives/C65MC3NSF/p1611344560006300
with the glitch https://glitch.com/edit/#!/naf-material-color that use a sphere in the html with `persistent:true`

**Comment by vincentfretin** [comment]
Another example we could add https://github.com/networked-aframe/networked-aframe/issues/232#issuecomment-764453299
A sphere with random color set by the first participant, the other participants see the same color. But the code was specific to the easyrtc adapter.

**Comment by vincentfretin** [comment]
When doing this example, look at the https://github.com/networked-aframe/networked-aframe/issues/178 issue about the different ownership events.

**Comment by vincentfretin** [comment]
There is actually the http://localhost:8080/ownership-transfer.html example that demonstrate how to spawn a cube and take ownership of it. We may adapt it to add a raycaster component?

**Comment by vincentfretin** [comment]
see also #258

**Comment by vincentfretin** [comment]
When the creator (not owner) of a networked entity leaves the room, the entity is removed from the room. Using `persistent:true` disable the removal.
In the code, if using `persistent:false` and if the creator field is empty, it fallback to owner, so the entities with creator unknown are removed if the current owner leaves. The only case where creator is empty is when you're specifying the owner yourself, but not the creator. So actually you can have persistent by specifying `persistent:false;creator:scene` but this is confusing. :)

`persistent:true;owner:scene` in the html, specifying a non empty owner string that isn't a real participant, is used so that the user that join the room won't send this entity because not the current owner, the creator field is actually empty but we don't care because `persistent:true`.

**Comment by hthetiot** [comment]
You can test it at https://naf-examples.glitch.me/ownership-transfer.html

Love it @vincentfretin
