### ISSUE TITLE
Mark webrtc adapter as wip and resurrect the easyrtc adapter

### ISSUE THREAD

**Issue by vincentfretin** [networked-aframe/networked-aframe#240]
The webrtc adapter is too new and didn't have much real production tests. I heard several reports that it was too buggy.
I propose to mark it as "work in progress, may contains issues". Leave it in this repo or move it back to the naf-webrtc-adapter repo that contains an old version of it at the moment. Though I don't have the permission in the other repositories yet.

I'm thinking about putting back the easyrtc adapter (server side updated with open-easyrtc) in the networked-aframe repo and modify the examples to use it by default (and update the urls to aframe 1.2.0 as well).
I'll probably keep the new simple socketio adapter, and don't reimport the wseasyrtc one. But it would mean having two separate servers in the examples I think.

Thoughts?

**Comment by vincentfretin** [comment]
We could maintain the easyrtc adapter in the separate repository https://github.com/networked-aframe/naf-easyrtc-adapter and point in the documentation how to use the external adapter, but it may not be a good first developer experience. I don't have the write permission on the naf-easyrtc-adapter repository yet, so for now I can't do that anyway.

**Comment by hthetiot** [comment]
Thx @vincentfretin , I'm the maintainer of open-easyrtc; let me know if I can assist with upgrading the original PR here https://github.com/networked-aframe/networked-aframe/pull/175

**Comment by hthetiot** [comment]
related https://github.com/networked-aframe/naf-easyrtc-adapter/pull/2

**Comment by vincentfretin** [comment]
Ah there are issues and PR there too :D Thanks @hthetiot 
Hayden gave me only the permission on networked-aframe repo, not the other repositories or the networked-aframe organization. I asked him but didn't hear back from him yet.
What would you prefer? Keep the naf-easyrtc-adapter in the separate repo now it's there or put it back in this repo?

**Comment by hthetiot** [comment]
@vincentfretin can you accept my LinkedIn request so we can disscuss in private ?

**Comment by msitarzewski** [comment]
@hthetiot are you on the Aframe slack? There are close to 10,000 there but I don't see you! We'd love to have you.

**Comment by hthetiot** [comment]
@vincentfretin I'm not on the slack, but i dont want to share my email here, can we have a short video call to disscuss before.

Join is broken anyway https://aframevr-slack.herokuapp.com/invite

<img width="1046" alt="Screenshot 2021-02-22 at 12 47 28" src="https://user-images.githubusercontent.com/8635/108704329-23772400-750c-11eb-8f06-b4eb3ae0d0d4.png">

**Comment by msitarzewski** [comment]
Use this one… I just grabbed it.

 

https://join.slack.com/t/aframevr/shared_invite/zt-f6rne3ly-ekVaBU~Xu~fsZHXr56jacQ

**Comment by vincentfretin** [comment]
You need to use the invite form here https://aframe.io/slack-invite/

**Comment by vincentfretin** [comment]
We're not in a hurry. :-)
Let's take the time to think about it. Thanks @hthetiot for wanting to help. I'll go back now to my current job and see all this probably this weekend. I'll ping you to review any PR I make.

**Comment by vincentfretin** [comment]
There was also a proposal to merge both wseasyrtc and easyrtc adapters in #80, not sure what do to about it.

**Comment by hthetiot** [comment]
> There was also a proposal to merge both wseasyrtc and easyrtc adapters in #80, not sure what do to about it.

I do recommand to have a pure ws easyrtc adapter. See comment https://github.com/networked-aframe/networked-aframe/issues/80#issuecomment-562552856

**Comment by vincentfretin** [comment]
Why don't you recommend it? I don't read the reason behind your comment. Some folks apparently want an simple adapter without audio/video, no RTCPeerConnection at all, only websocket. What's the alternative then? Do we keep the new simple socketio adapter then? The may be almost no difference between socketio adapter and wseasyrtc adapter because open-easyrtc is using socketio too.

**Comment by hthetiot** [comment]
I see, if people don't want WebRTC but want to use Easyrtc then why not.

**Comment by vincentfretin** [comment]
Some folks have WebRTC blocked on their network, so they want a solution without it, especially if they don't need audio.
With easyrtc adapter
sendData uses WebRTC datachannel and may fallback to websocket the comment said in the adapter
sendDataGuaranteed uses websocket.

With wseasyrtc, both sendData and sendDataGuaranteed use websocket.

**Comment by vincentfretin** [comment]
From the discussion in #139 it would be great to specify we want to use the websocket instead of datachannels for `sendData` in the easyrtc adapter. In the janus adapter you can specify for reliableTransport and unreliableTransport "datachannel", "websocket" or a function to use another server.

**Comment by vincentfretin** [comment]
I compared socketio and wseasyrtc adapters, I think the real difference is that wseasyrtc (and easyrtc adapter) with open-easyrtc is sending keepAlive commands every 20s. This is quite important, see #200 ah ah. So really I don't see any value using the socketio adapter over wseasyrtc adapter. The server side https://github.com/networked-aframe/networked-aframe/blob/62a94f3e0b56e40d465a8203b2f68a4200eb65a7/server/index.js is nice to learn how to write a simple server, but really it's too simple. :-)

**Comment by vincentfretin** [comment]
Quick note, until I close this issue and #241 you may want to use my fork of the Mozilla fork in the meantime, see
https://github.com/MozillaReality/networked-aframe/pull/45#issuecomment-782712933

**Comment by vincentfretin** [comment]
Like I said in https://github.com/networked-aframe/networked-aframe/issues/200#issuecomment-784860233 I'll keep both socketio/webrtc in this repository. I don't have permissions to move code in other repositories in the networked-aframe organization. And I don't want you folks to maintain a fork of your own if you're using the socketio adapter successfully with your own modified nodejs server for example. Is there anyone that did this? Let us know.
But keep in mind the socketio lacks any keepalive message, so you will have issues behind nginx #243 unless you implement something yourself in your app to send regularly a component update for example.

**Comment by LorenzoVonMatterhom** [comment]
@vincentfretin We want easyRTC back!
