### ISSUE TITLE
Unable to spawn networked entity

### ISSUE THREAD

**Issue by LorenzoVonMatterhom** [networked-aframe/networked-aframe#250]
I'm unable to spawn a netwoked entity: the a-entity is created locally but doesn't appear on other clients connected to the server.
```
var sceneEl = document.querySelector('a-scene');
  var entityEl = document.createElement('a-entity');
  entityEl.setAttribute('networked', {
    template: '#ball',
    attachTemplateToLocal: false
  });
  /*entityEl.setAttribute('geometry', {
    primitive: 'sphere',
    radius: 0.2
  });
  entityEl.setAttribute('dynamic-body', {
    linearDamping: 0.2,
    angularDamping: 0.2
  });
  entityEl.setAttribute('material', {
    color: "blue"
  });
  entityEl.setAttribute('position', { x: 0, y: 5, z: 0 });*/
  sceneEl.appendChild(entityEl);
```

...although i'm adding a new schema both when the scene is loaded and when the new entity is added:
```
NAF.schemas.add({
    template: '#ball',
    components: [
      'position',
      'rotation'
    ]
});
```
...which refers to the template:
```
<template id="ball">
          <a-entity class="ball" material="color: blue" position="0 5 0" rotation geometry="primitive: sphere; radius:0.2">
          </a-entity>
        </template>
```
Is this feature not implemented yet? Does NAF check every update if new networked entities are spawned?

**Comment by vincentfretin** [comment]
http://localhost:8080/ownership-transfer.html is a working example of spawning a cube and other participants see it immediately . Did you look at it?
From your code sample I don't see any obvious error.
Please provide a running example on glitch.com if you want additional help.

**Comment by LorenzoVonMatterhom** [comment]
@vincentfretin Thank you so much for the fast reply and the example: I hadnt looked at it and comparing it to my code i found only one difference:
`attachTemplateToLocal: false`
which apparently breaks the whole thing.
I removed that line and my code now works!

**Comment by vincentfretin** [comment]
Yes `attachTemplateToLocal: false` doesn't show the object locally, but it shows for the other participants. You use it for avatars for example.

**Comment by LorenzoVonMatterhom** [comment]
I may be wrong but in this case setting `attachTemplateToLocal: false` dinamically 
`entityEl.setAttribute('networked', {
    template: '#ball',
    attachTemplateToLocal: false
  });` was preventing NAF from showing the object on all other participants.
 On the other hand if you set it in HTML its viceversa, just like you said.
So this may be a bug.

**Comment by vincentfretin** [comment]
I use `entityEl.setAttribute('networked', { template: '#ball', attachTemplateToLocal: false })` in my app and I don't see the issue you're describing. It works properly. Please provide a glitch example where you can reproduce the issue.

**Comment by LorenzoVonMatterhom** [comment]
Yes, you were right. I havent been able to reproduce the issue so at this point it must have been javascript code not being executed for some reason. Thanks again!
