### ISSUE TITLE
New 0.8.0 release

### ISSUE THREAD

**Issue by vincentfretin** [networked-aframe/networked-aframe#253]
Not right now, but eventually in a week or two, release a 0.8.0 version to npmjs.com
Here is the commands I think I need to do:
- don't forget to update the version in `src/NafIndex.js` and `package.json`
- run `npm run dist` and commit the files
- `git tag 0.8.0` and `git push --tags`
- `npm login && npm publish`
- resync the naf-examples project on glitch (see https://support.glitch.com/t/possible-to-code-locally-and-push-to-glitch-with-git/2704/3)
- update the https://glitch.com/edit/#!/naf-project base template on glitch

Is there something I'm missing? It will be the first time I upload a release to npmjs.com :)

- [x] check the issue #178
- [x] write the release notes and link it from the README
- [x] publish to npmjs.com
- [ ] update examples on glitch when I'll have the edit permission
- [x] run the updated examples somewhere else than https://haydenlee.io/networked-aframe => done https://naf-examples.glitch.me

**Comment by vincentfretin** [comment]
Ah we also need to update all the glitch examples that are referenced in the documentation.
I just asked @haydenjameslee to give me te edit permission on them. Here is the list:
* [Nametags](https://glitch.com/edit/#!/naf-nametags)
* [Dynamic Room Name](https://glitch.com/edit/#!/naf-dynamic-room)
* [Form to set room and username](https://glitch.com/edit/#!/naf-form-example)
* [Glitch NAF Audio Example](https://glitch.com/edit/#!/networked-aframe-audio)
* [Edit live example on glitch.com](https://glitch.com/~networked-aframe)

**Comment by vincentfretin** [comment]
There is a https://github.com/networked-aframe/networked-aframe/blob/master/docs/RELEASE_NOTES.md file, I should probably add changelog entries there. The file is not currently referenced from the README.

**Comment by vincentfretin** [comment]
Some examples on https://haydenlee.io/networked-aframe like https://haydenlee.io/networked-aframe/ownership-transfer.html are not working at all, all js files return 404. We may need to use a different domain or just github.io for github pages to host the demo and modify all haydenlee.io links to point to the new location.
I didn't hear back from @haydenjameslee yet to have ownership on the glitch examples.

**Comment by vincentfretin** [comment]
I changed `src/NafIndex.js` and `package.json` to 0.8.0 and pushed the new builds, but it's not necessary those builds that will be officially in 0.8.0 (I didn't make the tag on purpose). It's just that you can easily reference the github master url https://raw.githubusercontent.com/networked-aframe/networked-aframe/master/dist/networked-aframe.min.js to have an up to date build to include in some external repo examples.

**Comment by vincentfretin** [comment]
Ah actually you can't use the raw.githubusercontent.com url in <script> because it's served as plain/text.
You can use jsdelivr, this works:
```
<script src="https://cdn.jsdelivr.net/gh/networked-aframe/networked-aframe@master/dist/networked-aframe.min.js" crossorigin="anonymous"></script>
```

**Comment by vincentfretin** [comment]
Ah about github pages... we can't use that because we still need a node server running for the examples. I think https://haydenlee.io/networked-aframe is on some personal Hayden server.
Maybe we can git push the examples to a glitch?
```
npm run preghpages
cd gh-pages
git init
git push .... ?
```

**Comment by vincentfretin** [comment]
Found back the comment from @kylebakerio https://aframevr.slack.com/archives/C0FAACNA0/p1611248322005700 about using git push with glitch. We should investigate if it can be easy to sync the examples folder this way on a glitch project. If anyone is interested to try that, please go ahead, write the instructions how you did it and give me the edit permission on the glitch project. I'll look into this otherwise in the following weeks.

**Comment by kylebakerio** [comment]
> Ah we also need to update all the glitch examples that are referenced in the documentation.
> I just asked @haydenjameslee to give me te edit permission on them. Here is the list:
> 
> * [Nametags](https://glitch.com/edit/#!/naf-nametags)
> * [Dynamic Room Name](https://glitch.com/edit/#!/naf-dynamic-room)
> * [Form to set room and username](https://glitch.com/edit/#!/naf-form-example)
> * [Glitch NAF Audio Example](https://glitch.com/edit/#!/networked-aframe-audio)
> * [Edit live example on glitch.com](https://glitch.com/~networked-aframe)

It would be good to have these since they are so well named, but I think we should move the contents of these to this github repo, or to this organization as a separate repo. It's actually pretty easy to deploy from a github repo to glitch--then we could allow pull requests on the glitches.

**Comment by kylebakerio** [comment]
I see now after reading the rest of the comments that you have foudn my old comments talking about this. :)

I actually copied that text to an aframe wiki that I haven't publicly released yet and formatted it there as well. I'd be interested in setting that up.

**Comment by vincentfretin** [comment]
Version 0.8.0 is published on https://www.npmjs.com/package/networked-aframe

**Comment by vincentfretin** [comment]
I still don't have access to the existing glitch projects to update them, this is unfortunate. :(

**Comment by vincentfretin** [comment]
I just imported the repo in glitch here https://naf-examples.glitch.me
This seems fine. I'll replace all haydenlee.io link with it.

**Comment by vincentfretin** [comment]
I marked the glitch projects that I don't have access to as "(not updated to latest version)" in https://github.com/networked-aframe/networked-aframe/commit/d37c234bbebf8f34ba4e06312a04733c45826f5e
and I created another base template on glitch called naf-project to replace the networked-aframe project on glitch in https://github.com/networked-aframe/networked-aframe/commit/e87a75b4d300c94287d8329dfdd86ff94dd892ef

**Comment by vincentfretin** [comment]
I wrote the release instructions and how to update glitch naf-examples in https://github.com/networked-aframe/networked-aframe/commit/5d696a5e7d5f99e9b55fd421600ba25179f13bfb
