### ISSUE TITLE
Add Streaming Video

### ISSUE THREAD

**Issue by kylebakerio** [networked-aframe/networked-aframe#260]
I have an initial implementation with the open-easyrtc adapter working locally that requires just a bit of updating to add here. It follows the semantic pattern of the `networked-audio-source` and its usage pattern. I should have some time to add it in early April.

In the future there is interest in adding multi-video/multi-audio support. In the [w3 spec](https://www.w3.org/TR/mediacapture-streams/#stream-api), it's indicated that this should be possible by adding multiple tracks to one stream, and then extracting the desired tracks as needed. That would be the lowest effort and cleanest implementation. However, it's possible that the spec isn't followed well here--it doesn't seem it was in the past. I plan to try a low-effort experiment to see if this works. If need, we can start looking at the updates needed to support multiple active mediastreams per user.

**Comment by vincentfretin** [comment]
@hthetiot did a great PR there #261 implementing a single video per user. Let's first review that.

**Comment by hthetiot** [comment]
I would recommend to close this issue and create separate issue for multistream.

Then i will add it to adapter based on janus adapter interface and ads sample with screenshare+webcam.

**Comment by vincentfretin** [comment]
ok, see #269
