### ISSUE TITLE
Your networked-aframe naf form from github

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [networked-aframe/networked-aframe#263]
Hello can someone tell me where i can download the networked-aframe networked-form-example from glitch please [here](https://glitch.com/~naf-form-example) ?

Joseph

**Comment by vincentfretin** [comment]
From the link you gave, you need to click on "View Source" button, and you have all the files on the left. You need to expand the public folder to see the html files.

**Comment by vincentfretin** [comment]
The code of this example is not on github currently.
If you want to git clone the glitch, see https://support.glitch.com/t/possible-to-code-locally-and-push-to-glitch-with-git/2704/2
This works fine:
```
git clone https://api.glitch.com/git/naf-form-example
```
