### ISSUE TITLE
Audio not working properly if clients are connecting from different networks

### ISSUE THREAD

**Issue by lazarmitic** [networked-aframe/networked-aframe#268]
If I try to open official sound [example](https://haydenlee.io/networked-aframe/basic-audio.html), it works if all clients are connecting from same network - for example multiple tabs in same browser, or browser and a phone connected to same wifi.

But if I try to connect from my PC and my phone (on mobile data), it does not work properly, sound is not going through, and I noticed that last message I get in console is `Waiting on audio for MNFxbgF7JsPUzHbI`, promise for getting the audio is never resolved, and `setMediaStream` is never called.

Same thing happens in my app hosted on firebase and easyrtc server hosted on digital ocean.

**Comment by vincentfretin** [comment]
Please don't use https://haydenlee.io it's a server that belongs to Hayden that I can't update. The example there is still using the webrtc adapter that is known to be buggy and is not maintained.
All examples are now on https://naf-examples.glitch.me
You can test the audio here https://naf-examples.glitch.me/basic-audio.html which now uses the easyrtc adapter that we maintain.

**Comment by lazarmitic** [comment]
Same thing happens here https://naf-examples.glitch.me/basic-audio.html - works fine on same network, does not work if users are on different network (IP).

**Comment by vincentfretin** [comment]
You may need to configure a TURN server. See https://github.com/networked-aframe/networked-aframe/blob/master/docs/hosting-networked-aframe-on-a-server.md#extra-steps-for-webrtc
You can look at the ICE candidate selected, in Firefox you can see it by tapping in the address bar about:webrtc and Chrome it's chrome://webrtc-internals/

When a new participant arrive you get:
```
Opening datachannel to  yCv8CWZdVFXquPpF
Creating remote entity {networkId: "fq7zyo7", owner: "yCv8CWZdVFXquPpF", creator: "yCv8CWZdVFXquPpF", lastOwnerTime: 1617044697632.125, template: "#avatar-template", …}
Waiting on audio for yCv8CWZdVFXquPpF
Successfully started datachannel to  yCv8CWZdVFXquPpF
Opened data channel from yCv8CWZdVFXquPpF
```
The important part is "Successfully started datachannel" after the "Waiting on audio", it means the WebRTC connection was successful.

**Comment by lazarmitic** [comment]
I will try that - thanks! :D

**Comment by vincentfretin** [comment]
If it can help you, you can read the documentation at 
https://github.com/open-easyrtc/open-easyrtc/blob/master/docs/easyrtc_server_ice.md
and 
https://github.com/open-easyrtc/open-easyrtc/blob/master/docs/easyrtc_common_problems.md
and maybe other files there, I'm not familiar with the open-easyrtc documentation.

**Comment by lazarmitic** [comment]
Thanks for all the help - it works now :)

**Comment by vincentfretin** [comment]
Can you share a little bit what was the issue? So you added a TURN server and this resolved your issue? Does the doc is still up to date regarding this? Contribution welcome to update it if it's not the case. Thanks.

**Comment by lazarmitic** [comment]
It was related to TURN server, when I added it, it started working. I also started using custom easyrtc adapter that you mentioned above.
