### ISSUE TITLE
Allowing a User to specify, upon entry, a url that hosts the mesh and texture of their preferred avatar?

### ISSUE THREAD

**Issue by Whystler** [networked-aframe/networked-aframe#271]
Is this possible?

**Comment by vincentfretin** [comment]
Of course it's possible. [Hubs](https://github.com/mozilla/hubs) is doing it as well as other solutions using networked-aframe.
You can achieve it with something like this:
- set `networked-scene="connectOnLoad: false"`
- create a `player-info` component with name and url data and add it to the avatar-template networked schema, in update function set `gltf-model` with the url on a child of `this.el`.
- create an entry form to select name and avatar url, and an "enter room" button, save the fields in localStorage or on the server if you want to be able to retrieve the info on several devices.
- when clicking on "enter room" button set the info on the component `player-info` on your avatar and call `AFRAME.scenes[0].emit('connect');`
