### ISSUE TITLE
Detect who is currently speaking

### ISSUE THREAD

**Issue by lazarmitic** [networked-aframe/networked-aframe#272]
Is there a way to detect who is currently speaking when using audio source? I want to update UI to show who is speaking - something like Google Hangouts white circles around user avatars.

**Comment by vincentfretin** [comment]
You have access to the audio track of each participant, you can analyze the volume of each audio track.
See the Hubs code for inspiration, specially the networked-audio-analyser component.
https://github.com/mozilla/hubs/search?q=networked-audio-analyser
