### ISSUE TITLE
Need newer buffered-interpolation version with newer threejs (r128)

### ISSUE THREAD

**Issue by vincentfretin** [networked-aframe/networked-aframe#280]
The documentation is wrong, we don't use [aframe-lerp-component](https://github.com/haydenjameslee/aframe-lerp-component) since may 2018 https://github.com/networked-aframe/networked-aframe/commit/e15f34250c2c28e00ade2c57cf94f9f0043f0c1b. We use [buffered-interpolation](https://github.com/InfiniteLee/buffered-interpolation) to update position, rotation, scale.
=> Update the README.md and CONTRIBUTING.md

**Comment by vincentfretin** [comment]
@netpro2k merged a similar PR https://github.com/InfiniteLee/buffered-interpolation/pull/7
Does somebody other than @InfiniteLee have the right to publish a new version on npmjs.com?

**Comment by vincentfretin** [comment]
Note that the slerpQuaternions change is not compatible with aframe 1.2.0 / three r125, so I won't include this change in a new networked-aframe version until aframe updates threejs to at least r128.

**Comment by vincentfretin** [comment]
If you have your own aframe build with threejs r128, you can create your own networked-aframe build with in `package.json`:
```
"buffered-interpolation": "github:Infinitelee/buffered-interpolation"
```

**Comment by vincentfretin** [comment]
Folks are still using aframe 1.0.4 or 1.1.0 with latest networked-aframe. So if aframe updates threejs and we update networked-aframe to use the latest version of buffered-interpolation, it would mean networked-aframe won't support old aframe versions anymore. :(

Maybe we can find a way to support both deprecated and new api in buffered-interpolation in our own fork? We will think about it again when aframe update to recent threejs.

**Comment by vincentfretin** [comment]
I don't think adding a condition to check THREE version in the [`InterpolationBuffer.slerp`](https://github.com/InfiniteLee/buffered-interpolation/blob/1940a8202019f0c5ecc0e25ae43c292b8cc449d7/index.js#L61-L63) method would be a good idea for perf reason, because this is executed on each tick.
Maybe define `this.slerp` inside the InterpolationBuffer class constructor to define a different slerp method based on THREE version? I didn't test but maybe something like that could work?

```
class InterpolationBuffer {
  constructor(mode = MODE_LERP, bufferTime = 0.15) {
    if (parseInt(THREE.REVISION, 10) < 128) { // or lower 126 or 127?
      this.slerp = function(target, r1, r2, alpha) {
        THREE.Quaternion.slerp(r1, r2, target, alpha);
      }
    } else {
      this.slerp = function(target, r1, r2, alpha) {
        target.slerpQuaternions(r1, r2, alpha);
      }
    }
    
    // ....
  }
```

**Comment by vincentfretin** [comment]
What do you folks think? Do I need to bother about compatibility with older aframe/threejs like this?
Or just release aframe 0.9.0 compatible only with aframe 1.3.0? It means that all new improvements to naf won't be usable for aframe older than 1.3.0.

**Comment by arpu** [comment]
i think we should loose compatibility for aframe < 1.3.0, and look forward
