### ISSUE TITLE
Updating API for updating element components that are `attachTemplateToLocal=false`

### ISSUE THREAD

**Issue by kylebakerio** [networked-aframe/networked-aframe#295]
Moving from pull request [here](https://github.com/networked-aframe/networked-aframe/pull/290#issuecomment-937915706) into this issue.

> It doesn't create the entities when attachTemplateToLocal is false.

I thought so, thanks for clarifying.

> For 1, As a developer I don't expect those invisible entities to be created if attachTemplateToLocal is false. Depending on your template, this could have side-effects like downloading some resources like textures you didn't expect, and those may never be used for rendering. This really depends on your app use case though.

Yeah, this could incur some level of performance cost in theory in a few ways, but I think the effect is pretty minor. As long as `visible=false`, I don't think it will incur rendering burden, which is the most important thing, I'd think. It does create the best developer experience, though, imo. This is similar to what you suggested a few comments back, when you said:

> If you set attachTemplateToLocal:true with visible:false does it works correctly? Maybe this would be simpler to understand?<sup>[1](https://github.com/networked-aframe/networked-aframe/pull/290#issuecomment-915879899)</sup>

(The difference is that the dev shouldn't have to manually add a partial copy of the template, though)

Nothing special is needed. We could rename `attachTemplateToLocal` to something else to be more clear--we could also just add this as an alternate mode and leave both, depending on what is needed by the dev and to prevent breaking existing code. `attachTemplateToLocal=false` for when the dev wants to make sure the template is completely not present / incurs no burden, and something like `hideLocalTemplate=true` as an alternative that just uses `visible=false` so they can propagate networked changes using the standard A-Frame component apis while still hiding it locally. 

> For 2, I understand it, but I'm not sure how this API could look like. Do you have an API design in mind?

This is just a quick draft off the top of my head; I really appreciate how NAF in most cases works so that nothing like this is necessary, but I also _really dislike_ how it can need something like shown in the demos to share changes when `attachTemplateToLocal` is false, and I think this is a reasonable stab at a compromise.

Here's two idea for how this could look, along with an example scenario to make it clear:

```html
<a-scene>
    <a-assets>
      <template id="net-sphere">
        <a-entity class="outer-sphere" geometry="primitive: sphere" material="color: red">
           <a-entity class="inner-box" geometry="primitive: box" material="color: yellow"></a-entity>
        </a-entity>
      </template>
    </a-assets>
    <a-entity id="my-net-sphere" networked="template:#net-sphere; attachTempalteToLocal:false;"></a-entity>
</a-scene>

<script>
    // (1) we add a special method to 'networked' component called `setAttribute` that works similarly to the A-Frame `setAttribute` 
    // that would be used this way (though should also accept
    document.querySelector('#my-net-sphere').components['networked'].setAttribute('.outer-sphere','material', 'color', 'red')
    // (1b) should also allow this syntax, to match what is enabled by A-Frame's `el.setAttribute`:
    document.querySelector('#my-net-sphere').components['networked'].setAttribute('.outer-sphere', { material: { color: 'orange' } } })
    
    // (2) declare a custom schema handler for a special property, e.g. 'naf-update' here, to create a way of using the built-in 
    // `setAttribute` for the `networked` component 
    // note: this would require this object-style syntax, because we're using the built-in `el.setAttribute` method
    document.querySelector('#my-net-sphere').setAttribute('networked', 'naf-update', { '.inner-box' { material: { color: 'blue' } } })
    
    // (3a) special global function we add for modifying things that don't exist locally
    NAF.setAttribute('#my-net-sphere', '.inner-box', 'material', 'color', 'green')
    // (3b) again, the global should also allow this syntax
    NAF.setAttribute('#my-net-sphere', { '.outer-sphere': { material: { color: 'orange' } } })
</script>
```

The idea is that when you use this, if you are using it on something with `attachTemplateToLocal=true` it does nothing special, but if it's with `attachTemplateToLocal=false` and the piece of the template is missing locally, then it would either:

- silently add in the necessary element, and then continue in the future by updating invisible, newly created element, OR:
- as per (3), just propoagate the change to peers without actually locally adding the missing template element/component

> I talked about localStorage because I have the connectOnLoad:true in mind and also as a user I don't want to reenter my name every time, but yes for demos we can simply generate random nametags and allow to change it when in the room via an overlay.
If you change to connectOnLoad:false, you can prompt for a nametag and color before joining the room.

yeah, exactly. I also generally just don't add `networked-scene` until I'm ready and make a wrapper component to handle that logic, but same idea.

**Comment by vincentfretin** [comment]
Using `attachTemplateToLocal:true` with `visible=false` and putting the `random-color` in the template works properly. I agree the rendering performance shouldn't be a problem. Here is the diff:
```
diff --git a/examples/basic-audio.html b/examples/basic-audio.html
index 2444e2d..9da06ad 100644
--- a/examples/basic-audio.html
+++ b/examples/basic-audio.html
@@ -32,6 +32,7 @@
         <template id="avatar-template">
           <a-entity class="avatar" networked-audio-source>
             <a-sphere class="head"
+              random-color
               scale="0.45 0.5 0.4"
             ></a-sphere>
             <a-entity class="face"
@@ -67,16 +68,12 @@
       </a-assets>
 
       <a-entity id="player"
-        networked="template:#avatar-template;attachTemplateToLocal:false;"
+        networked="template:#avatar-template;attachTemplateToLocal:true;" visible="false"
         camera
         position="0 1.6 0"
         spawn-in-circle="radius:3"
         wasd-controls look-controls
         >
-        <a-sphere class="head"
-          visible="false"
-          random-color
-        ></a-sphere>
       </a-entity>
 
       <a-entity position="0 0 0"

```

After some thought, I don't think we need a special API to update component properties on non existing entities. I found it to be harder to understand than what we currently have actually.
I think the API you're describing can be achieved more or less with a component like "player-info" having color and nametag properties on the same entity as the networked component, and apply the color to `.head` if it exists. I'm doing just this actually on one of my project. It uses API you already know without introducing new ones you need to learn and understand.

Here a diff of the basic-audio example:
```
diff --git a/examples/basic-audio.html b/examples/basic-audio.html
index 2444e2d..dcf67c0 100644
--- a/examples/basic-audio.html
+++ b/examples/basic-audio.html
@@ -13,6 +13,30 @@
     <!--<script src="https://unpkg.com/aframe-particle-system-component@1.0.5/dist/aframe-particle-system-component.min.js"></script>-->
     <script src="https://cdn.jsdelivr.net/gh/oneWaveAdrian/aframe-particle-system-component@aframe-1.2.0-upgrade/dist/aframe-particle-system-component.min.js"></script>
     <script src="/js/spawn-in-circle.component.js"></script>
+  <script>
+AFRAME.registerComponent('player-info', {
+  schema: {
+    color: {type: 'string', default: "#ffffff"},
+    nametag: {type: 'string', default: "Bob"}
+  },
+
+  init: function() {
+    const color = '#' + new THREE.Color(
+      Math.random(),
+      Math.random(),
+      Math.random()
+    ).getHexString();
+    this.el.setAttribute('player-info', 'color', color);
+  },
+
+  update: function() {
+    const head = this.el.querySelector('.head');
+    if (head) {
+      head.setAttribute('material', 'color', this.data.color);
+    }
+  }
+});
+  </script>
   </head>
   <body>
     <a-scene networked-scene="
@@ -30,7 +54,7 @@
 
         <!-- Avatar -->
         <template id="avatar-template">
-          <a-entity class="avatar" networked-audio-source>
+          <a-entity class="avatar" networked-audio-source player-info>
             <a-sphere class="head"
               scale="0.45 0.5 0.4"
             ></a-sphere>
@@ -67,16 +91,12 @@
       </a-assets>
 
       <a-entity id="player"
-        networked="template:#avatar-template;attachTemplateToLocal:false;"
+        networked="template:#avatar-template;attachTemplateToLocal:false;" player-info
         camera
         position="0 1.6 0"
         spawn-in-circle="radius:3"
         wasd-controls look-controls
         >
-        <a-sphere class="head"
-          visible="false"
-          random-color
-        ></a-sphere>
       </a-entity>
 
       <a-entity position="0 0 0"
@@ -121,17 +141,17 @@
         components: [
           'position',
           'rotation',
-          {
-            selector: '.head',
-            component: 'material',
-            property: 'color'
-          }
+          'player-info'
         ]
       });
 
       // Called by Networked-Aframe when connected to server
       function onConnect () {
         console.log("onConnect", new Date());
+        const player = document.getElementById('player');
+        if (player) {
+          player.setAttribute('player-info', 'nametag', 'Alice');
+        }
 
         // Handle mic button click (Mute and Unmute)
         micBtnEle.addEventListener('click', function() {
diff --git a/server/easyrtc-server.js b/server/easyrtc-server.js
```

You can't use the `random-color` component in the template here because `attachTemplateToLocal:false`. If you do, each of the other participants will see you with a different color. So I'm doing the random color in player-info init here.

If you want to see your own avatar, you can use `attachTemplateToLocal:true` and put the `random-color` component in the template. Here is the diff:
```
diff --git a/examples/basic-audio.html b/examples/basic-audio.html
index 2444e2d..a346385 100644
--- a/examples/basic-audio.html
+++ b/examples/basic-audio.html
@@ -13,6 +13,17 @@
     <!--<script src="https://unpkg.com/aframe-particle-system-component@1.0.5/dist/aframe-particle-system-component.min.js"></script>-->
     <script src="https://cdn.jsdelivr.net/gh/oneWaveAdrian/aframe-particle-system-component@aframe-1.2.0-upgrade/dist/aframe-particle-system-component.min.js"></script>
     <script src="/js/spawn-in-circle.component.js"></script>
+  <script>
+AFRAME.registerComponent('player-info', {
+  schema: {
+    nametag: {type: 'string', default: "Bob"}
+  },
+
+  update: function() {
+    // do something with this.data.nametag
+  }
+});
+  </script>
   </head>
   <body>
     <a-scene networked-scene="
@@ -30,8 +41,9 @@
 
         <!-- Avatar -->
         <template id="avatar-template">
-          <a-entity class="avatar" networked-audio-source>
+          <a-entity class="avatar" networked-audio-source player-info>
             <a-sphere class="head"
+              random-color
               scale="0.45 0.5 0.4"
             ></a-sphere>
             <a-entity class="face"
@@ -67,16 +79,12 @@
       </a-assets>
 
       <a-entity id="player"
-        networked="template:#avatar-template;attachTemplateToLocal:false;"
+        networked="template:#avatar-template;attachTemplateToLocal:true;" player-info
         camera
         position="0 1.6 0"
         spawn-in-circle="radius:3"
         wasd-controls look-controls
         >
-        <a-sphere class="head"
-          visible="false"
-          random-color
-        ></a-sphere>
       </a-entity>
 
       <a-entity position="0 0 0"
@@ -121,6 +129,7 @@
         components: [
           'position',
           'rotation',
+          'player-info',
           {
             selector: '.head',
             component: 'material',
@@ -132,6 +141,10 @@
       // Called by Networked-Aframe when connected to server
       function onConnect () {
         console.log("onConnect", new Date());
+        const player = document.getElementById('player');
+        if (player) {
+          player.setAttribute('player-info', 'nametag', 'Alice');
+        }
 
         // Handle mic button click (Mute and Unmute)
         micBtnEle.addEventListener('click', function() {
```

**Comment by kylebakerio** [comment]
(just a tip--I've edited your comment, but you can still use ` ```html` even if it's malformed html because of the git diff syntax to get some highlighting, which will make it easier to read than having no highlighting)

**Comment by kylebakerio** [comment]
This looks very promising. I assumed there was an edge case that must exist to justify the awkward examples, but if no special syntax is needed to handle that case, that's great. I indeed have my own workaround that don't require any special syntax on my own projects that are pretty similar to this, but this is more minimalist and 'pure NAF', and mine rely on some internal tooling I had built out, so this is definitely ideal. I'll go make a stab at updating the glitch along these lines and update when I've done so.

**Comment by kylebakerio** [comment]
So, running with that example and refactoring more, I think we can actually get it down to a much more intuitive and clear form:

first we patch utils, for now (open to better ideas for this, but this is the best option I've come up with so far)
```js
      NAF.utils.ownedByLocalUser = function ownedByLocalUser(el) {
          return new Promise(async (resolve, reject) => {
            const ownerId = await NAF.utils.safelyGetOwner(el)
            resolve(ownerId === NAF.clientId)
          })
        }
  
        NAF.utils.safelyGetOwner = function safelyGetOwner(el) {
          return new Promise(async (resolve, reject) => {
            const netEl = await NAF.utils.getNetworkedEntity(el)
            const ownerId = netEl.components.networked.data.owner
            resolve(!ownerId || ownerId !== NAF.clientId ? ownerId : NAF.clientId)
          })
        }
```

Then, the player-info component:
```js
      AFRAME.registerComponent('player-info', {
        schema: {
          color: {
            type: 'string', 
            default: '#' + new THREE.Color( Math.random(), Math.random(), Math.random() ).getHexString()
          },
          nametag: {type: 'string', default: "user-" + Math.round(Math.random()*10000)},
        },
      
        init: function() {
          this.head = this.el.querySelector('.head');
          NAF.utils.ownedByLocalUser(this.el).then(local => {
            if (local) {
              document.querySelector("#username-overlay").value = this.data.nametag;
              document.querySelector("#username-overlay").oninput = () => {
                this.data.nametag = document.querySelector("#username-overlay").value
              };
            }
            console.log("userlist", [...document.querySelectorAll('[player-info]')].map(el => el.components['player-info'].data.nametag))
          })
        },
      
        update: async function(newArgs) {
          // console.log(this.data, newArgs)
          try {
            this.head.setAttribute('material', 'color', this.data.color);
          } catch (e) {
            console.warn("will benignly fail when this.head doesn't exist, which is the case for local user.")
          }
        }
      });
```

In the HTML, I am kind of wondering if `attachTemplateToLocal:false;` is necessary...? Can't we just always use `visible="false"` instead? In your example, you see `player-info` both in the template _as well as_ in the scene itself, which is not ideal / confusing for new users. I think it's cleaner this way, and I'm really wondering what are the reasons to even use `attachTemplateToLocal:false;`, am I missing/forgettting/overlooking something?

you can see my implementation draft here (same place as it has been): https://glitch.com/edit/#!/8-2021-naf?path=examples%2Ftracked-controllers.html%3A97%3A0

**Comment by kylebakerio** [comment]
> On your above code snippet, the update signature doesn't seem right, it should be:

I realized I could actually ignore this. Basically, because `setAttribute()` already checks and ignores duplicates, I don't need to also check in my own update function.
