### ISSUE TITLE
Connecting spaces seamlessly?

### ISSUE THREAD

**Issue by runvnc** [networked-aframe/networked-aframe#303]
Hello, is it possible to make a clickable link that brings you to another networked-aframe space? I assume it works the same as any other web link in A-frame. Is it possible to do that while keeping them in the VR environment?

Guessing this is related: https://github.com/immersive-web/navigation

**Comment by vincentfretin** [comment]
Hello,

This is indeed related to WebXR Navigation. I didn't test that myself, it should be possible with current Oculus browser on the same domain.

We had this discussion some days ago on Slack here
https://aframevr.slack.com/archives/C0FABCPJQ/p1635036986002700
This used to work with the old WebVR https://medium.com/samsung-internet-dev/webvr-navigation-in-samsung-internet-for-gearvr-3fd88c91e0a6 
For WebXR, this is now https://github.com/immersive-web/navigation and not currently fully implemented in all WebXR supported browsers.
See https://www.youtube.com/watch?v=jzIMQfp47zw from one month ago:
"navigation is currently being experimented within the Oculus browser for only traveling between web pages in the same first-party domain"

**Comment by vincentfretin** [comment]
Also thread on twitter from today
https://twitter.com/AdaRoseCannon/status/1455276484302675969

**Comment by runvnc** [comment]
Thanks so much for the info. But this has literally been implemented before. Call me crazy, but my inner cynic suspects the lack of support just might have something to do with Facebook's plan for owning "the Metaverse". Leaving this feature out of their browser may be an attempt to cripple the open Metaverse. Hopefully Firefox still supports it.
