### ISSUE TITLE
VR Scaling help

### ISSUE THREAD

**Issue by jryebread** [networked-aframe/networked-aframe#304]
Hi all! thanks for making this awesome library.

My goal is to scale up the player who is using VR in the tracked-controllers example, while the PC players should be normal size. Would very much appreciate help with this:

I have set all players to 10x the scale in the example, by just editing the a-entity in tracked-controllers.html
![image](https://user-images.githubusercontent.com/22125118/140692639-2f9cd984-2f87-4dfa-9868-07eae0c89c41.png)

https://pastebin.com/8VfRvs9V

However, the VR user head/avatar is not scaled the same as the PC users. Why is the VR user smaller than the PC users? Is there some code automatically scaling down the VR user somewhere? also, as the vr user, my hands are so small! Yet they appear huge to the other players 
![image](https://user-images.githubusercontent.com/22125118/140692803-3b97150a-5c15-4d1f-b968-d629fc779ea9.png)

![image](https://user-images.githubusercontent.com/22125118/140692823-83e3cbbe-30d9-4f03-933a-918282b4156c.png)

**Comment by jryebread** [comment]
I would really appreciate help trying to achieve my goal of enlarging the VR user avatar and hands while keeping the pc players small, i am still trying to wrap my head around the library, also I was not able to access the slack channel invite for help.

**Comment by jryebread** [comment]
Sure, is there already a pre-existing glitch template for the tracked controllers example i can add my code to?

**Comment by jryebread** [comment]
Nevermind, found it! here is my code: https://kindly-sugary-minotaurasaurus.glitch.me/

**Comment by vincentfretin** [comment]
I noticed you have a html syntax issue here
```
<a-entity scale="10 10 10 "class="avatar" player-info>
```
that should be
```
<a-entity scale="10 10 10" class="avatar" player-info>
```
I don't know if there is really an impact here, it doesn't seem so.

Your line
```
el.object3D.scale.set(5000, 500, 500)
```
is setting a pretty big scale. Is it normal you have 5000 instead of 500 for x?

You set `scale="10 10 10"` on the camera-rig, actually overridden to scale 500 for VR users in your tracked-vr-hands component , that is why you are super high in the sky. 10x1.6=16m on desktop, and 500x1.6=800m on VR (may be higher if your height is more than 1.6m).

Instead of changing the scale on each entity, you should just set it to camera-rig-template that is the parent for the head and the hands. But if you only want VR users to appear giant, leave the scale to 1 on camera-rig-template, add a networked schema for camera-rig-template to sync the scale component (this is probably your missing bit to achieve the thing you want), and in the enter-vr listener set the scale to 10 on the user camera rig (like you currently do with your scale 500).
So if you get back the original example, the following changes should be good I think?
```js
diff --git a/examples/tracked-controllers.html b/examples/tracked-controllers.html
index 9123635..7f8e9ea 100644
--- a/examples/tracked-controllers.html
+++ b/examples/tracked-controllers.html
@@ -46,15 +46,16 @@
           // networked entities, no schema declaration is necessary. If we did
           // include it, though, it would look like this:
 
-          // if (!NAF.schemas.hasTemplate("#camera-rig-template")) {
-          //   NAF.schemas.add({
-          //     template: '#camera-rig-template',
-          //      components: [
-          //       'position',
-          //       'rotation',
-          //     ]
-          //   });
-          // }
+           if (!NAF.schemas.hasTemplate("#camera-rig-template")) {
+             NAF.schemas.add({
+               template: '#camera-rig-template',
+                components: [
+                 'position',
+                 'rotation',
+                 'scale',
+               ]
+             });
+           }
 
           // likewise for the left-hand-template and right-hand-template--since we're only
           // syncing position/rotation, no schema declaration needed!
@@ -79,6 +80,7 @@
           // add these with JS:
           // <a-entity hand-controls="hand:left" networked="template:#left-hand-template;attachTemplateToLocal:true;"></a-entity>
           // <a-entity hand-controls="hand:right" networked="template:#right-hand-template;attachTemplateToLocal:true;"></a-entity>
+          this.el.object3D.scale.set(10, 10, 10);
           ['left', 'right'].forEach(side => {
             const el = document.createElement('a-entity')
             el.setAttribute('hand-controls', {hand: side});
diff --git a/server/easyrtc-server.js b/server/easyrtc-server.js
```

**Comment by jryebread** [comment]
Oh my gosh it works! Thank you so much! Can you send me an invite to the aframe slack channel btw please? :)

**Comment by vincentfretin** [comment]
From https://github.com/aframevr/aframe/pull/4941
https://aframe.io/slack-invite/ seems dead
Can you please try https://aframevr.slack.com/join/shared_invite/zt-f6rne3ly-ekVaBU~Xu~fsZHXr56jacQ
If this works, I'll update the links in the doc.

**Comment by jryebread** [comment]
this link worked, thx again ill close this ticket

**Comment by vincentfretin** [comment]
Thanks for letting me know. I fixed the links in https://github.com/networked-aframe/networked-aframe/commit/f668c2de16372fd0294b6359e129303551b41df8
