### ISSUE TITLE
NAF+ Cesium maps ?

### ISSUE THREAD

**Issue by jimver04** [networked-aframe/networked-aframe#311]
Hi Vincent,

have you seen this Cesium maps + Aframe component ?

https://github.com/anselm/aterrain

It would be nice to have also multiplaying feature there.

Have you seen my pull request ?

Thanks,
D. Ververidis

**Comment by vincentfretin** [comment]
Hi,
I seen your PR, it's open in a tab in my browser to look at it. I'll look at it all tomorrow.

**Comment by jimver04** [comment]
nice, 
drop me a call in skype for a short discussion if you have time:                jimver78 
For more than 3 players, sometimes the video stops. Can we make to load the videos on the fly ? I think all players should be aboard in order to start the secondary video stream. The primary stream (video camera) is automatically shutdown to save some bandwidth. 
Best,
D.

**Comment by vincentfretin** [comment]
Actually I found out about this old terrain component a few days ago when searching for something else and I ended up reading old mozilla blog posts. Here is the post:
https://blog.mozvr.com/introducing-a-terrain/
This terrain component is 4 years old.
The example https://anselm.github.io/aterrain/examples/helloworld/tile.html is using a cesium endpoint which currently return 401, probably the access key doesn't work anymore.
Do you have an example with a working endpoint?

I'm not familiar how this component work. I just looked quickly at it. I'm not sure what you want to synchronize for multiusers here? Can you change or does the component change maybe the latitude, longitude, elevation of the a-terrain component when you move? I have no idea, hard to tell without a working example.
But if this is it, I guess you can create a networked schema that sync those properties for the a-terrain component and define a persistent networked component to have the same instance between participants. You will need to takeOwnership of the a-terrain component every time you change properties of the a-terrain component. 

Also not the same component, but if you're interested in the maps subject, did you see the recent 3dtiles component?
https://twitter.com/kfarr/status/1481839525546524673?t=KtUhcq6mR-ukbjETy4mbDQ
https://twitter.com/NYTimesRD/status/1481640791466397706?t=eNy7Uz8AYlndoAl9LxBXPw
https://twitter.com/the_ross_man/status/1482074683205992458?t=ewTbSOOX-rhuyaEW3_w9qA
https://twitter.com/kfarr/status/1482894260911308802?t=Dy5i8kYzFX1FwNe6qUjKJQ
