### ISSUE TITLE
Not able to run from a single page application

### ISSUE THREAD

**Issue by Andrewvanbeek** [networked-aframe/networked-aframe#335]
The glitch apps work great, but I was hoping to run it from a single App.  User goes to SPA -----> Node js backend with socket.io ----> then response is sent back to the client of the new user.  However when I initialize I keep on getting this error: "io is not defined"

Aframe code in Vue js`
  <a-scene
      networked-scene="
      room: basic;
      debug: true;
      serverURL: ws://concise-iced-oyster.glitch.me;
    "
    >
      <a-assets>
        <img
          id="grid"
          src="https://img.gs/bbdkhfbzkk/stretch/https://i.imgur.com/25P1geh.png"
          crossorigin="anonymous"
        />
        <video id="webcam" class="webcam" ref="webcam" playsinline></video>
        <img
          id="sky"
          src="https://img.gs/bbdkhfbzkk/2048x2048,stretch/http://i.imgur.com/WqlqEkq.jpg"
          crossorigin="anonymous"
        />
        <a-asset-item
          id="glbtestmodel"
          src="https://cdn.glitch.global/e3f37049-787f-41c0-b8f0-4d4d6b5f0273/mm_project%20(4).glb"
        >
        </a-asset-item>

        

        
        <template id="avatar-template">
          <a-entity>
            <a-plane position="0 3 2" shadow material="src: #webcam"></a-plane>
            <a-entity
              gltf-model="#glbtestmodel"
              class="avatar"
              animation-mixer="clip: DoStuff;"
            >
            </a-entity>
          </a-entity>
        </template>

        
      </a-assets>

      <a-entity
        id="player"
        camera
        networked="template:#avatar-template;attachTemplateToLocal:false;"
        position="0 1.6 0"
        spawn-in-circle="radius:3"
        wasd-controls
        look-controls
      >
        <a-sphere class="head" visible="false" random-color></a-sphere>
      </a-entity>

      <a-entity
        position="0 0 0"
        geometry="primitive: plane; width: 10000; height: 10000;"
        rotation="-90 0 0"
        material="src: #grid; repeat: 10000 10000; transparent: true; metalness:0.6; roughness: 0.4; sphericalEnvMap: #sky;"
      ></a-entity>

      <a-entity
        light="color: #ccccff; intensity: 1; type: ambient;"
        visible=""
      ></a-entity>
      <a-entity
        light="color: #ffaaff; intensity: 1.5"
        position="5 5 5"
      ></a-entity>

      <a-sky src="#sky" rotation="0 -90 0"></a-sky>
      <a-entity id="particles" particle-system="preset: snow"></a-entity>
    </a-scene>

`

**Comment by vincentfretin** [comment]
Using aframe in a react or vuejs component is not supported. You need to include the scene directly in the html file in some way.
