### ISSUE TITLE
sync oculus quest controles whit avatar

### ISSUE THREAD

**Issue by CamiloB** [networked-aframe/networked-aframe#336]
hi im trying to sync the oculus quest 2 controllers whit the avatar, on pc i can see the both avatars and the pc avatar can move around whit the keypad, but on the oculus the character of the oculus stay on the spawn site the head is sync whit the oculus, but the avatar is not, on oculus you can move around but the avatar is not moving whit the camera here is the code:

     <a-entity id="rig">
            <a-entity id="camera" position="0.72035 1.45 0" rotation="0 0 0">
                   <a-entity id="player" velocity="0 0 2.170137447532053e-19" twoway-motion="speed: 70"
                    networked="template:#avatar-template;attachTemplateToLocal:true;" position="0 2 0"
                    spawn-in-circle="radius:3" wasd-controls="acceleration: 100" kinematic-body="mass: 1; radius: 0.5"
                    look-controls camera rotation-get>
                    <a-sphere class="cuerpoSup" visible="false"></a-sphere>
                    <a-box class="cabeza" visible="false" rotation-set></a-box>
                    <a-entity oculus-touch-controls="hand: left" oculus-thumbstick-controls ></a-entity>
                    <a-entity oculus-touch-controls="hand: right" oculus-thumbstick-controls ></a-entity>    
                    <a-cursor>
                    </a-cursor>
                </a-entity>
            </a-entity>
          </a-entity>

**Comment by vincentfretin** [comment]
Hi, we can't help you with just the snippet you gave. Please give a full reproducible example on glitch. Did you base your code on the [tracked-controllers](https://github.com/networked-aframe/networked-aframe/blob/master/examples/tracked-controllers.html) example? See also the commented code and explanation if you you want the hands to be networked.

**Comment by CamiloB** [comment]
hi vincent thanks for the reply the traked controllers for oculus quest 2 does not work thats why i use other controls here is the full code of the project 

Here is the aframe version
    <script src="https://aframe.io/releases/1.0.3/aframe.min.js"></script>
    <script src="https://unpkg.com/aframe-randomizer-components@^3.0.1/dist/aframe-randomizer-components.min.js"></script> 

here is the sokets  and the networked aframe
 <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.slim.js"></script>
 <script src="https://unpkg.com/networked-aframe@^0.8.0/dist/networked-aframe.min.js"></script>

here im using this controls for the oculus that worked just fine
<script src="https://gftruj.github.io/webzamples/aframe/controls/oculus-thumbstick-controls.js"></script>


            <a-entity id="rig">
            <a-entity id="camera" position="0.72035 1.45 0" rotation="0 0 0">
                              
                <a-entity id="player" velocity="0 0 2.170137447532053e-19" twoway-motion="speed: 70"
                    networked="template:#avatar-template;attachTemplateToLocal:true;" position="0 2 0"
                    spawn-in-circle="radius:3" wasd-controls="acceleration: 100" kinematic-body="mass: 1; radius: 0.5"
                    look-controls camera rotation-get>
                    <a-sphere class="cuerpoSup" visible="false"></a-sphere>
                    <a-box class="cabeza" visible="false" rotation-set></a-box>
                    <a-entity oculus-touch-controls="hand: left" oculus-thumbstick-controls  ></a-entity>
                    <a-entity oculus-touch-controls="hand: right" oculus-thumbstick-controls ></a-entity>    
                    <a-cursor>

                    </a-cursor>
                </a-entity>
            </a-entity>
          </a-entity>


that all the code that i have

**Comment by vincentfretin** [comment]
Please provide an example based on [naf-project glitch template](https://glitch.com/~naf-project) that uses latest aframe 1.3.0 and networked-aframe 0.9.1. I don't support old versions.
You have two choices, add the hands with a selector in avatar-template schema or add networked component on each hand that have their schema like the tracked-controllers commented code.

**Comment by vincentfretin** [comment]
Does the tracked-controllers example works correctly with the Quest 2? It worked when I tried last time with the Quest 1.
