### ISSUE TITLE
NAF schemas add option to only sync Y axis rotation

### ISSUE THREAD

**Issue by kevinsuwito** [networked-aframe/networked-aframe#339]
I'm trying to use a humanoid avatar for players, but with the current default component sync, the avatar rotates up and down while also rotating left and right. I want the avatar to only rotate left and right (Y axis only).

Is there an option to specify which axis to sync in NAF schema, probably something like this:

```
NAF.schemas.add({
  template: '#avatar-template',
  components: [
    'position',
    {
      selector: '.avatar-model',
      component: 'rotation',
      property: 'y'
    }
  ]
});
```

**Comment by vincentfretin** [comment]
You can't do that. The rotation component has a single non named property `{type: 'vec3'}`.
What you can do is create a `rotation-y-only` component you put on your avatar-model entity with a tick method that reset to 0 the xz rotation for example:
```
AFRAME.registerComponent('rotation-y-only', {
  tick: function() {
    if (this.el.id === 'player') return;
    const rot = this.el.object3D.rotation;
    this.el.object3D.rotation.set(0, rot.y, 0);
  }
}
```
