### ISSUE TITLE
networked-video-source Error

### ISSUE THREAD

**Issue by Vesper-0407** [networked-aframe/networked-aframe#341]
when I try to append the `networked-video-source` to the entity, it went wrong and the camera dispalyed nothing. The console errors: `Error getting media stream for PlURQIbUt8tNCngx Interface method not implemented: getMediaStream`
Would you please help me out?

**Comment by vincentfretin** [comment]
The examples are working properly as far as I can tell. Please provide an example triggering the issue on glitch if you still have the issue, and on which browser you had the issue. Thanks.
