### ISSUE TITLE
easyrtc-server VS adapters

### ISSUE THREAD

**Issue by Racheal1064** [networked-aframe/networked-aframe#346]
This may be a dummy question, but I am a little confused.

In my understanding, easy-rtc server itself enables Webrtc communication on the web, otherwise, a simple https server may serve the purpose. So why would there still be need to employ different adapters for clients' web communications?

**Comment by Racheal1064** [comment]
Or this server serves as a signaling server?

**Comment by vincentfretin** [comment]
The easyrtc server indeed serves as a signaling server.

The wseasyrtc adapter is using websocket to transfer naf data (avatar position and rotation for example), and to know the participants connected to a room to broadcast the data to them. There is no audio, no video with this adapter.

The easyrtc adapter is using the websocket only for signaling part, the naf data flows through a WebRTC datachannel of the peer to peer connection to each participant in the room. You can have audio and video with WebRTC.

You can read the wiki page https://github.com/networked-aframe/networked-aframe/wiki/NAF-adapters-comparison if you want to learn more.
