### ISSUE TITLE
Problem while doing combine with aframe-extras

### ISSUE THREAD

**Issue by RepSklvska** [networked-aframe/networked-aframe#349]
I made it combined for networked-aframe and aframe-extras in my testing project. Now I got a problem: When the other user joined, the previous user existed in the scene can't control with movement or rotation anymore. Anyone have the idea on this?

**Comment by vincentfretin** [comment]
I see your created https://github.com/n5ro/aframe-extras/issues/379 as well that is somewhat related?
You can look at https://github.com/AdaRoseCannon/aframe-xr-boilerplate for an example that uses the blink-controls component for teleportation.
