### ISSUE TITLE
Doesn't work :(

### ISSUE THREAD

**Issue by TheRealDigitalMaster** [networked-aframe/networked-aframe#371]
When I try to use this, I test it by opening it in 2 seperate tabs. When I try to see the other player, no one is there. Should I open it in my browser or on a github.io website?

**Comment by vincentfretin** [comment]
What did you test?

You need to open the page via a hosted url or your local node server, so downloaded through a web server yes, don't open the index.html file in your browser, it won't work.

First test https://naf-examples.glitch.me/basic.html that is using wseasyrtc adapter.
Then test https://naf-examples.glitch.me/basic-audio.html that is using easyrtc adapter, so with WebRTC involved.
If the first works and the second doesn't, you may need a turn server.

**Comment by TheRealDigitalMaster** [comment]
Ok thanks 👍
