### ISSUE TITLE
Multiplayer doesn't work.

### ISSUE THREAD

**Issue by TheRealDigitalMaster** [networked-aframe/networked-aframe#373]
When I open the file in my browser, I tested it out with my brother, but it doesn't work (doesn't show the other player).

**Comment by vincentfretin** [comment]
Same issue as #371 ?
Do you have an error in the console? Right click then inspect or F12 then look at the console tab.
Did you start the node server with `npm start`?
You didn't open the html file itself right? That won't work.
What url did you open? It should include the ip of your machine.
Does your brother are on the same network?

**Comment by TheRealDigitalMaster** [comment]
I am on a chromebook, so I don't have access to the function keys, and if I did, I wouldn't be able to use inspect element because I am blocked by family link. So I am looking for games to create/play with multiplayer. And yes, I opened the .html file itself because localhost is blocked on my account as well. And my brother is on the same network or else the scaledrone chat I made wouldn't work.

**Comment by TheRealDigitalMaster** [comment]
And how do I open `npm start`? Is there a github app I should have?

**Comment by vincentfretin** [comment]
Did you follow the tutorial? https://github.com/networked-aframe/networked-aframe/blob/master/docs/getting-started-local.md
You need to have nodejs on your machine that host the experience, and start the easyrtc server.

**Comment by TheRealDigitalMaster** [comment]
And I just looked on aframe.io (or probably an imatation I forgot the link), and when I tried out the other multiplayer code, it works, but I can't move.

**Comment by TheRealDigitalMaster** [comment]
I think it's because it was aframe version 1.2.0 not 1.3.0

**Comment by vincentfretin** [comment]
You're really not giving much information about your experience, where it's hosted, the scenario you tested, which url, so I can't help you further. You should first start with the naf-project template on glitch, or the getting started tutorial with a local nodejs server, make that work with two users accessing the same glitch url or local on http://ip:8080 . I can still help with those, but I can't help with an unknown experience of yours.

**Comment by TheRealDigitalMaster** [comment]
I have to ask my parents for every website I want, including http://ip:8080 and http://localhost:8000 so I might just be opening the .html file directly. Thanks! 👍

**Comment by vincentfretin** [comment]
You need to replace ip by your machine ip address on your network, so something like 192.168.1.15. That's not even a domain name, does this also needs to be whitelisted? For localhost, you should be able to use 127.0.0.1 instead.
