### ISSUE TITLE
Stun servers at 80 or 443

### ISSUE THREAD

**Issue by jimver04** [networked-aframe/networked-aframe#378]
In the wifi I want to test naf seem that 
 {"urls":"stun:stun1.l.google.com:19302"},
 {"urls":"stun:stun2.l.google.com:19302"}

ports are blocked. 

I have tried to use 
    {"urls":"stun:openrelay.metered.ca:80"},
    {"urls":"stun.nextcloud.com:443"}

but no luck. 

![image](https://user-images.githubusercontent.com/1898502/202127182-1968ac1a-65c0-4953-9a94-fa7876f287bf.png)

Do you know any reliable stun servers at 80 or 443 port ?

Best,
Dimitrios

**Comment by jimver04** [comment]
ok 
this
{"urls":"stun:openrelay.metered.ca:80"}
seem to work fine.

I have to write it alone without the nextcloud. 
Is there any reason that you put two servers in the list ?

Best,
Dimitrios

**Comment by vincentfretin** [comment]
I didn't use [openrelay](https://www.metered.ca/tools/openrelay/) myself but I saw it before yes, be sure to read their [terms](https://www.metered.ca/tools/openrelay/terms-and-conditions/).
[Xirsys](https://xirsys.com/) works well for me, they have a free tier that is probably enough for simple needs, they also give you urls for stun and turn on 80 and 443 ports.

Which two servers are your talking about, google stun? If one fail, it ask on the second url, that's it.

**Comment by jimver04** [comment]
I have no idea why STUN is not working for smartphones in public networks. 

From [here](https://webrtc.ventures/2020/12/webrtc-signaling-stun-vs-turn/) I see that TURN is just a proxy:
"A TURN (Traversal Using Relays around NAT) server goes around the network address, essentially traversing the connection using relays. So when a STUN server cannot establish a connection between the two parties, the TURN server steps in as an intermediary."

I guess having 3 or 4 smartphones to do some experiments won't cause them heavy burden. It is only for signaling isn't it?

I will add also Xirsys just in case the openrelay doesn't work. 

If I add a STUN server, will the smartphone automatically select the TURN server and the Desktop/Laptop the STUN server?  Can two different servers / technologies can be used for one room in EasyRTC/NAF ?

thanks!
Dimitrios

**Comment by vincentfretin** [comment]
You usually configure those urls:
```
"stun:{turn_host}",
"turn:{turn_host}:80?transport=udp",
"turn:{turn_host}:80?transport=tcp",
"turns:{turn_host}:443?transport=tcp",
```
