### ISSUE TITLE
User names?

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [networked-aframe/networked-aframe#384]
Hello, I'm having a problem where I have a lot of people playing on my server and I can not tell who is who. Is there a way to give user names to each user above there heads or somwthing?

**Comment by vincentfretin** [comment]
Hello, see the [Nametags + Color Picker](https://naf-examples.glitch.me/nametag.html) example.

**Comment by Therealjosephchrzempiec** [comment]
Hello Thank you. I notice on the server side it displays  [RCWuPzx2GHO1ZNJK] is there a way to match the user name enter to  the server name?

**Comment by vincentfretin** [comment]
Those are clientId and are generated by open-easyrtc library, and need to be unique for each participant, that can't be true if you use username here.

**Comment by Therealjosephchrzempiec** [comment]
Ohh,I see.I'm trying the shooter demo I was trying to figure out a way to give users points for hitting the other user. I though I would need the name of the back end server to do that. Coding is not my strong point. My skills are in hardware. But I'm trying to learn.

I just need to figure out how to give health to the user and how to kill the other user in the scene. I'm working on a simple shooter game.
