### ISSUE TITLE
Is it possible to display mirror image of the video in `networked-video-source`

### ISSUE THREAD

**Issue by Vesper0704** [networked-aframe/networked-aframe#385]
Maybe I can set the \<video\> style `transform: rotateY(180deg)` to achieve it(in setupVideo()). Is there any other approach by setting instead of changing the source code?

**Comment by vincentfretin** [comment]
I think `scale="-1 1 1"` on the a-plane should work, but I didn't test.

**Comment by Vesper0704** [comment]
It works. Thanks!
