### ISSUE TITLE
Adjusting the Inactivy user?

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [networked-aframe/networked-aframe#386]
Hello, I notice after sometime the user in aframe seem to get disconnected for being inactive after sometime. Is there a way to stop that. And just let the user be on full time?

Joseph

**Comment by vincentfretin** [comment]
Hello, it shouldn't disconnect, the socket is pinged regularly to not close normally.
Please give us more information.
Which adapter? easyrtc?
How much time exactly? 30s 60s 120s?
Hosted where?
Do you access nodejs directly?
Is this behind nginx?
Which version of networked-aframe?
Which version of socketio?
Which version of open-easyrtc do you have? 2.0.17? look at node_modules/open-easyrtc/package.json
What logs do you have when it happens?

**Comment by Therealjosephchrzempiec** [comment]
hello, I'm hosting it locally. On a ubuntu desktop system. I installed node. I have installed the lastest networked-aframe. I have changed or modded anything Just straight out of the box. Everything that came with networked-aframe I used I have not added anything. 

I'm unsure what easyrtc adapter that is. Which one that comes with networked-aframe. I do not know of nginx. I have never used it. the socketio I have no no idea I'm guessing the one that comes with it. 

All I did was installed networked-aframe and node then ran it that is all.

Joseph

**Comment by Therealjosephchrzempiec** [comment]
i think I found my problem. And its a user error problem. That would be me. I forget my laptop goes to sleep. When that happens It loses the connection. Yay. Sorry for teh bother and trouble of this Post. Please close or delete it out.

Joseph

**Comment by Therealjosephchrzempiec** [comment]
Hello, What I have notice is that If I leave the tab and go to another tab on the browser after some time Which I don't know how long maybe after 10 or 10 maybe longer I need to see that the player goes away and it freezes up. When Igo back to the tab of the networked-aframe it is frozen and I can not move. When I go to the server and look at terminal it shows that my player has disconnected. and if I hit refresh it comes back.

**Comment by vincentfretin** [comment]
Hello, I don't know the details but Chrome is slowing down some javascript execution for background tabs, that may be related.
https://stackoverflow.com/questions/6032429/chrome-timeouts-interval-suspended-in-background-tabs

**Comment by vincentfretin** [comment]
The discussion continued on #390
