### ISSUE TITLE
charnging ports?

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [networked-aframe/networked-aframe#387]
Hello, I asked this Question before. But I can not find it anymore. I'm trying to change port from 8080 to a Different port How can I change it?

Joseph

**Comment by vincentfretin** [comment]
You can use 
```
PORT=8090 npm run dev
```
or change the port 8080 to something else like 8090 in `server/easyrtc-server.js`

**Comment by Therealjosephchrzempiec** [comment]
I have tried to run it as PORT=8090 npm run dev when ran it just only ran as port 8080. And when I changed the port in server/easyrtc-server.jsI it runs. it works. Thank you. To bad I can not run it as port 80. But that is okay.

**Comment by vincentfretin** [comment]
What do you use on Windows? Terminal? It indeed probably not work this way. I don't know how you set environment variables in Windows Terminal.
The way to set inline environment variable like I described is working with bash shell, it should work on Windows with WSL with Ubuntu too.
There is another way:
```
export PORT=8090
npm run dev
```
but again with bash shell.

**Comment by Therealjosephchrzempiec** [comment]
I'm running networked-aframe on ubuntu server locally. In windows I'm just using putty to access the ubuntu server and just running Screen session that's all.
