### ISSUE TITLE
NPM install errors.

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [networked-aframe/networked-aframe#389]
Hello, When I try to install npm inside the networked-aframe I get nothing but errors. here are a few.
`
npm ERR! git clone --template=/home/tester2250/.npm/_git-remotes/_templates --mirror git://github.com/infinitelee/buffered-interpolation.git /home/tester2250/.npm/_git-remotes/git-github-com-infinitelee-buffered-interpolation-git-5bb18421ebf2bf11664645cdc7a15bd77ee2156b-5ca8d08a: Cloning into bare repository '/home/tester2250/.npm/_git-remotes/git-github-com-infinitelee-buffered-interpolation-git-5bb18421ebf2bf11664645cdc7a15bd77ee2156b-5ca8d08a'...
npm ERR! git clone --template=/home/tester2250/.npm/_git-remotes/_templates --mirror git://github.com/infinitelee/buffered-interpolation.git /home/tester2250/.npm/_git-remotes/git-github-com-infinitelee-buffered-interpolation-git-5bb18421ebf2bf11664645cdc7a15bd77ee2156b-5ca8d08a: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/tester2250/.npm/_git-remotes/_templates --mirror git://github.com/infinitelee/buffered-interpolation.git /home/tester2250/.npm/_git-remotes/git-github-com-infinitelee-buffered-interpolation-git-5bb18421ebf2bf11664645cdc7a15bd77ee2156b-5ca8d08a: github.com[0: 140.82.112.4]: errno=Connection timed out
npm ERR! Linux 4.15.0-202-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
WARN engine webrtc-adapter@8.2.0: wanted: {"npm":">=3.10.0","node":">=6.0.0"} (current: {"node":"8.10.0","npm":"3.5.2"})
`

This is a new ubuntu installed system. I have install node already as well as git And other things as well as fully updated system. I just can not get npm to install can someone please hrlp me and let me know what I'm missing or doing wrong?

Joseph

**Comment by vincentfretin** [comment]
` github.com[0: 140.82.112.4]: errno=Connection timed out`
 github was momentarily unavailable I guess, try again later?

**Comment by Therealjosephchrzempiec** [comment]
I was also having nodejs problems. So I purge that and reinstalled now that is okay.

I manage to npm install. But whe I try to run it I get theses errors now.

`npm run dev

> networked-aframe@0.11.0 dev /home/tester2250/Documents/networked-aframe
> cross-env NODE_ENV=development node ./server/easyrtc-server.js

sh: 1: cross-env: not found

npm ERR! Linux 4.15.0-202-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! networked-aframe@0.11.0 dev: `cross-env NODE_ENV=development node ./server/easyrtc-server.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the networked-aframe@0.11.0 dev script 'cross-env NODE_ENV=development node ./server/easyrtc-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the networked-aframe package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node ./server/easyrtc-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs networked-aframe
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls networked-aframe
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tester2250/Documents/networked-aframe/npm-debug.log
tester2250@tester2250-NUC6CAYH:~/Documents/networked-aframe$


`

**Comment by vincentfretin** [comment]
It seems that `npm install` didn't install the devDependencies for whatever reason.
See https://stackoverflow.com/questions/34700610/npm-install-wont-install-devdependencies

**Comment by Therealjosephchrzempiec** [comment]
So ode and npm is messing up. This is strange.

**Comment by Therealjosephchrzempiec** [comment]
Is this a problem with npm or node, Or is it A ubuntu problem being on a 22.04?

**Comment by vincentfretin** [comment]
I don't have any issue with ubuntu 22.04 and node 16 from https://github.com/nodesource/distributions
Does `npm install --dev` work for you?

**Comment by Therealjosephchrzempiec** [comment]
that doesn't work errors.

**Comment by vincentfretin** [comment]
Ok I can't help you further. You need to search why it doesn't install the devDependencies on your install.

**Comment by Therealjosephchrzempiec** [comment]
I'm doing that actually. There is a problem right now with npm.

**Comment by Therealjosephchrzempiec** [comment]
To get installed for ubuntu you need to install nodejs and npm as well as git if you are doing it from a Clean install correct? Also All the ubuntu updates as well. Is there anything missing?

**Comment by Therealjosephchrzempiec** [comment]
hello, Just an update. I wiped the server clean with a new ubuntu installed and downloaded and installed everything. Then I installed npm and it ran networked-aframe with no problem now. Thank you
