### ISSUE TITLE
Nametag: Not a issue but a question.

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [networked-aframe/networked-aframe#391]
Hello, I'm using the nametag example. But I have a question. Is it possible to load the whole scene before letting the user enter? the reason why I'm asking is because I have a large scene and it takes a little time to load and I would like load my whole then the users avatars load.

Joseph

**Comment by vincentfretin** [comment]
Hello, yes it's possible, see the relevant section in the documentation:
https://github.com/networked-aframe/networked-aframe#connecting
You need to write your own ui with a button where you call `AFRAME.scenes[0].emit('connect');` on click.

**Comment by vincentfretin** [comment]
There was an old example showing it https://glitch.com/edit/#!/naf-nametags with a crude prompt. Slightly modified code here:
```js
function onSceneLoad() {
  let username = 'user-' + Math.round(Math.random() * 10000);
  username = prompt('Choose a username', username);
  const player = document.getElementById('player');
  const myNametag = player.querySelector('.nametag');
  myNametag.setAttribute('text', 'value', username);
  AFRAME.scenes[0].emit('connect');
}

document.addEventListener('DOMContentLoaded', () => {
  const scene = document.querySelector('a-scene');

  if (scene.hasLoaded) {
    onSceneLoad();
  } else {
    scene.addEventListener('loaded', onSceneLoad);
  }      
});
```

replace the prompt by your own UI with your favorite js and css frameworks.
