### ISSUE TITLE
Share Screen Issue

### ISSUE THREAD

**Issue by mrMUB** [networked-aframe/networked-aframe#402]
I have been trying to find a solution to an issue where when person A shares their screen, person B is able to see it. However, if person B refreshes the screen while person A is still sharing their screen, person B is no longer able to see the shared screen. This appears to be a known issue:

From Example: [basic-multi-streams.html](https://github.com/networked-aframe/networked-aframe/blob/master/examples/basic-multi-streams.html)
      Known issues with this demo, some cases are not handled:
      - If participant A shares their screen, the partipant B sees the other participant's screen.
        When participant A stops their screen share, the other participant will see a frozen screen, the last image received.
      - If participant A starts screen share, stops, and restarts the screen share, the other participant won't see it.

Can anyone offer any assistance in resolving this problem?

**Comment by vincentfretin** [comment]
Changes in #421 fix the issues.
