### ISSUE TITLE
stuck with npm i on a RPi Zero

### ISSUE THREAD

**Issue by Utopiah** [networked-aframe/networked-aframe#408]
I'm tinkering with the most affordable possible hardware for an inclusive social VR solution. I have a RPi Zero at home that could work quite well. I tried `npm i` a few time but despite not showing any particular error it does not seem to finish even after 45min or so. It might be due to having to recompile a lot for its architecture but hard to say.

<img width="1513" alt="image" src="https://user-images.githubusercontent.com/1076655/231672202-7263f113-9a07-40f4-842c-bf6e2330f0e6.png">

Anyway the point being `node_modules` takes on another architecture about 220Mb which seems like quite a bit. I'm wondering if there is an easy way to trim it down for much smaller projects.

Edit: killed the process yet `207M    node_modules/` so probably quite close to having everything. I'll let it run for hours and report back.

**Comment by Utopiah** [comment]
Well seems patience, and `npm run dev`, did the trick. Would still be curious about a "light" setup but closing for now. Hope it helps others.

**Comment by vincentfretin** [comment]
Yeah you don't need all the tests dependencies on the Raspberry.
You can just do this
```
cp package-glitch.json package.json
```
Your `node_modules` will be much lighter. This what I do when I deploy the examples on glitch.

**Comment by vincentfretin** [comment]
If you want to play with the janus adapter on Raspberry to have like 20 users in a LAN, the docker image works, but see the comments in the [Dockerfile ](https://github.com/networked-aframe/janus-plugin-sfu/blob/51394c9be388e2978faf4d593b99ecfadb3f6d7f/docker/Dockerfile#L2-L9). You can read about my experiments [here](https://github.com/networked-aframe/janus-plugin-sfu/pull/4#issuecomment-1140252832).

**Comment by Utopiah** [comment]
Damn, from 220Mb to 33Mb, nice! Glad I asked.

**Comment by Utopiah** [comment]
Made an image available at https://fabien.benetou.fr/Cookbook/Electronics#SocialWebXRRPi0
