### ISSUE TITLE
networked-hand-controls issues with aframe-v1.5.0

### ISSUE THREAD

**Issue by bruce90j** [networked-aframe/networked-aframe#450]
The networked-hand-controls component doesn't work properly with aframe-v1.5.0:
1. Hand color is not updated (example: `networked-hand-controls="hand:left;color:gold;"`).
    To make it work replace:
    https://github.com/networked-aframe/networked-aframe/blob/0f8452331d1d62fed9a76aaf4ab29961c1cc064e/src/components/networked-hand-controls.js#L219-L220
    with:
    ```
    const handColor = this.data.color;
    newMesh.traverse(function (object) {
        if (!object.isMesh) { return; }
        object.material.color = new THREE.Color(handColor);
    });
    ```

2. Hand controller does not work if controllerComponent is not specified (example: `networked-hand-controls="hand:right;handModelStyle:controller;"`).
    Remove `'gearvr-controls', 'daydream-controls'` from the `controllerComponents` list:

    https://github.com/networked-aframe/networked-aframe/blob/0f8452331d1d62fed9a76aaf4ab29961c1cc064e/src/components/networked-hand-controls.js#L235-L249

**Comment by vincentfretin** [comment]
Can you please create a PR?

**Comment by vincentfretin** [comment]
PR is #451
