### ISSUE TITLE
HOW TO SHOW ACTIVE AVATAR INFRONT OF CAMERA

### ISSUE THREAD

**Issue by BharatKumarAcademy** [networked-aframe/networked-aframe#464]
HOW TO SHOW ACTIVE AVATAR INFRONT OF CAMERA. CURRENTLY ONLY CAMERA IS SEEN. MEANS SOME OFFSET BETWEEN CAMERA AN D AVATAR

**Comment by vincentfretin** [comment]
You just lost your chance to get help from me, no need to yell.

**Comment by BharatKumarAcademy** [comment]
please provide solution
