### ISSUE TITLE
Audio not working in latest master

### ISSUE THREAD

**Issue by haydenjameslee** [networked-aframe/networked-aframe#52]
@netpro2k I tested the the positional audio PR in, merged it, then merged @robertlong's adapter registration PR. The positional audio seems not to be working, however I can't currently test it because my PC is acting up and no WebRTC audio samples are working at all. Could you check to make sure its working?

**Comment by haydenjameslee** [comment]
Arghhhh I forgot the networked-audio-source in the template I was testing with on glitch!

**Comment by haydenjameslee** [comment]
Here's the glitch project to test with: https://shadow-bead.glitch.me/

**Comment by netpro2k** [comment]
Perhaps we should have it spit out a warning if audio is enabled but no `networked-audio-source`es exist? Not sure when exactly this check would happen though...
