### ISSUE TITLE
example for sync besides avatar sync

### ISSUE THREAD

**Issue by 42loop** [networked-aframe/networked-aframe#53]
Maybe I'm just too bad at js, but i tried this since some time now:
run a networked scene on a local server. avatar sync example is running great.
now if i add any other object to the scene (onkeydown or explicit html), it should appear for each other user, which it does
but: the readme states:
> By default, the position and rotation components on the root entity are synced.

however, if i move the object either by animation or click-drag component, the object does not move for the other user.
i tried with template(analog to avatar), which supposedly isnt needed, i searched for other examples but all of them rely on firebase or so, which atm i dont want to use.
someone mentioned on twitter that its not easy to sync other objects, but i cannot find this any more and the discussion was moved to a moz dev forum...
maybe i'm missing something, any pointers appreciated

**Comment by haydenjameslee** [comment]
RE: discussion - All of the discussion for Networked-Aframe happens in the networked-aframe channel on the A-Frame Slack ([invite link](https://aframevr-slack.herokuapp.com/)) and this is open to all WebVR developers. 

RE: Syncing other objects - This does work, there must be something broken in your implementation. Please post some example code so we can help you debug, and for the best help put a simple example up on Glitch.com and post the link here. We can then remix the Glitch project to make it work for you.

**Comment by haydenjameslee** [comment]
It also would be useful to make an official example showing how to do this.

**Comment by mauriciomartinez-itesm** [comment]
Yes I haven't been able to sync objects either... I'm using a dynamic-body object so that might affect, nevertheless, what is happening, is that it's creating one instance of the object for each player that connects to the server, but that's it, no rotation/position gets synced.  @haydenjameslee told me that objects with physics are not yet supported, I'm commenting here since you're having a similar problem.

**Comment by haydenjameslee** [comment]
@mauriciomartinez-itesm would you be able to post a glitch project that shows the problem? I'll make a project myself to confirm its working (or not) as far as I'm understanding the problem.

**Comment by mauriciomartinez-itesm** [comment]
sure, [here's](https://glitch.com/edit/#!/torch-drizzle) the project... sorry for the mess and the spanish comments

**Comment by haydenjameslee** [comment]
Could you explain what's supposed to happen and what's actually happening that's incorrect?

**Comment by mauriciomartinez-itesm** [comment]
Yes, please ignore all the things that are not NAF...
There's supposed to be a dynamic-cube that's lying there (it's supposed to be one to be shared by all) players have a feet-cube so they can move the dynamic-cube it around (with wasd)

Instead of having one cube for all, I get one cube for every person that connects, and theirs positions are not shared, so a player can move them, but the other player won't see anything besides the movement of the player (not the cubes)

**Comment by haydenjameslee** [comment]
Gotcha. What you're seeing isn't a bug. The use case you're describing isn't supported out of the box with NAF. Its one of the next features we'd like to add, usually referred to as a "singleton entity". Currently when you create a networked entity, either dynamically with javascript or statically in the HTML, that client will create a new entity which will be created for everybody else. If you have two clients you'll have two entities.

One way to get around this is the idea of a "master" client that is solely responsible for creating such entities. See: https://github.com/networked-aframe/networked-aframe/issues/61

**Comment by antoniohof** [comment]
I tried to sync the visible attribute, but it does not work.
Whenever a change the attribute, it does not sync.
I have registered it in the schema, and changed it with vue data binding.
Tried to change also with the usual setAttribute, but also does not work...

```
      var speakingSchema = {
        template: '#speaking-icon-template',
        components: [
          'visible'
        ]
      }
      window.NAF.schemas.add(speakingSchema)

        <script id="speaking-icon-template" type="text/html">
          <a-entity id="speaking" visible="false">
            <a-image src="#speaking-icon-image" position='0 0.85 0'></a-image>
          </a-entity>
        </script>

          document.getElementById('speaking').setAttribute('visible', false)
```

Thanks

**Comment by haydenjameslee** [comment]
@antoniohof if you're still running into issues please open a new issue.

@42loop this example has been added: https://github.com/networked-aframe/networked-aframe/blob/master/server/static/shooter-2.html
