### ISSUE TITLE
Basic-audio.html does not work on iOS

### ISSUE THREAD

**Issue by Vamoss** [networked-aframe/networked-aframe#56]
As pointed in the https://github.com/networked-aframe/networked-aframe/issues/2#issuecomment-298836302:  
`This is most likely due to webrtc not being supported on iOS.`

After changing the basic-audio.html, line 41, to:
`adapter: wseasyrtc;`

The voice still not being transmitted from/to the iPhone.

Using wseasyrtc makes the iPhone see the other players, but no audio.
And using easyrtc, there is no audio and no players.

**Comment by haydenjameslee** [comment]
Are you on iOS 11?

The `wsEasyRTC` adapter doesn't support audio so that behaviour is expected. See the [adapter docs](https://github.com/networked-aframe/networked-aframe#adapters).

**Comment by antoniohof** [comment]
@Vamoss I think easyrtc works on IOS on the newest beta branch of easyrtc:

https://github.com/priologic/easyrtc/issues/335

https://github.com/priologic/easyrtc/tree/beta

**Comment by haydenjameslee** [comment]
I don't have an iOS device available so if somebody could look into this issue that'd be great

**Comment by haydenjameslee** [comment]
@Vamoss can you confirm you're having this issue with this example: https://networked-aframe-audio.glitch.me/

**Comment by haydenjameslee** [comment]
Also make sure you're running the app with HTTPS.

**Comment by MiyazawaK** [comment]
Doesn't work in iOS (11.1.2 on iPod touch) for me either (both, basic-audio.html and https://networked-aframe-audio.glitch.me/)

**Comment by Vamoss** [comment]
Oh, I don't know why I wasn't notified about the updates in this topic, I will take a look as soon as I can.

Cheers!

**Comment by Vamoss** [comment]
I did what @antoniohof suggested, and migrate the easyrtc module to beta branch, to accomplish that, you just need to run:
`npm install git://github.com/priologic/easyrtc.git#beta --save`

Now iPhone can send it's voice, but does not hear anything. We were able to solve this with the easyrtp example by adding the `playsinline="playsinline"` parameter, as suggested [here](https://github.com/priologic/easyrtc/issues/335).

We couldn't find how to insert parameter with the a-frame workflow.

**Comment by hthetiot** [comment]
See #355

**Comment by antoniohof** [comment]
https://github.com/networked-aframe/networked-aframe/pull/75

**Comment by haydenjameslee** [comment]
I can't test this myself since I don't have an iOS device available, but it makes sense to me.

**Comment by haydenjameslee** [comment]
I'm assuming this is fixed. If not, post here and I'll re-open.

**Comment by hthetiot** [comment]
#422
