### ISSUE TITLE
Networked A-Frame Doesn't Connect Unless I Refresh the Page

### ISSUE THREAD

**Issue by gabrieljbaker** [networked-aframe/networked-aframe#58]
I'm running into this issue on both Firefox and Chrome. My scene will say that "Networked AFrame is connecting....." but won't then connect and give me a clientID. As soon as I refresh the page, it connects and give me the clientID. Has anyone else run into this issue?

**Comment by haydenjameslee** [comment]
Does this happen with all NAF scenes you create? If you can repro with a glitch scene post it here.
