### ISSUE TITLE
Getting Started tutorial missing build.js

### ISSUE THREAD

**Issue by MilesMcBain** [networked-aframe/networked-aframe#60]
I was following the Getting Started tutorial and I have run into a problem trying to reproduce your output for `basic.html`. I do not see any avatars and I see the following errors in my javascript console in my browser:

* `Failed to load resource: the server responded with a status of 404 (Not Found) build.js`
*  `Uncaught ReferenceError: NAF is not defined at basic.html:16`

I'm a total node noob but it I think the problem here is that the tutorial assumes I am working from the networked-aframe dev environment, even though it told me to simply create a folder and install the npm dependencies. So for the tutorial to work `build.js` needs to be replaced with a link to `node_modules/networked-aframe/dist/networked-aframe.js`? 

I tried this but the only way I could get it to work is if I copied `networked-aframe.js` over to `./server/static/`.

Please let me know if I have missed something elementary.

**Comment by MiyazawaK** [comment]
Same for me. 
Including `<script src="https://unpkg.com/networked-aframe/dist/networked-aframe.min.js"></script>` made it work for me, but I have the feeling it's not intended to work like this.
Would appreciate an updated tutorial too!

**Comment by haydenjameslee** [comment]
Sorry about this! I updated the examples to fallback to the CDN script. It will be fixed once we release 0.5. In the meantime please replace build.js with `<script src="https://unpkg.com/networked-aframe/dist/networked-aframe.min.js"></script>` as @MiyazawaK suggested.
