### ISSUE TITLE
Master & slave

### ISSUE THREAD

**Issue by aliy321** [networked-aframe/networked-aframe#61]
Is there a way to create a master control for " admin " and when he trigger action it will change everyone's view?

**Comment by haydenjameslee** [comment]
Yes this is doable.

How do you wish to designate who is master?

Once you have worked out who the master is. Allow them to trigger an action that sends a broadcast to all clients using this API: https://github.com/networked-aframe/networked-aframe#sending-custom-messages

Then the other clients receive the message and do whatever you wish them to do.

**Comment by aliy321** [comment]
Master can see controls to change sky, slave cannot see control. How do i set who's the master?

**Comment by haydenjameslee** [comment]
That's entirely up to you! How do you wish to choose who's master? One way could be a URL parameter.

**Comment by haydenjameslee** [comment]
Here's an example of getting url parameters in A-Frame: https://github.com/haydenjameslee/networked-a-painter/blob/master/src/components/multiuser-mode.js#L48
