### ISSUE TITLE
This component conflicts with the aframe-template-component

### ISSUE THREAD

**Issue by mattrei** [networked-aframe/networked-aframe#62]
Hi,

due to name clashing of _template_ with  [Kevin's template-component](https://github.com/ngokevin/kframe/tree/master/components/template) those two components cannot be used together. 

Currently there is no way to overcome this. How should we address it? Who is wiling to rename its component?

Best

**Comment by arpu** [comment]
this component uses this
https://github.com/networked-aframe/networked-aframe/blob/master/package.json#L32

**Comment by haydenjameslee** [comment]
NAF uses Kevin's template component directly, so you have access to it already and you don't need to include it again.

**Comment by arpu** [comment]
is it possible do not use the template? 
(because i have problem with react and the template loading https://github.com/ngokevin/kframe/issues/106)

**Comment by mattrei** [comment]
i think its better to declare it as peerDependency then, not?

**Comment by haydenjameslee** [comment]
Currently the only way networked-aframe works is with the template component.
