### ISSUE TITLE
NAF.connection.getConnectedClients lags behind the clientDisconnected events

### ISSUE THREAD

**Issue by mattrei** [networked-aframe/networked-aframe#65]
Hi,

when I want call the _getConnectedClients_ within the _clientDisconnected_ event, the returned list does not resemble the list of connected clients you would expect, but the old data. I think it should resemble the connected clients, so the user has not to maintain the state himself.

See this glitch, and check error logs in after the _clientDisconnected_ event:
https://networked-aframe-connected.glitch.me

Best

**Comment by haydenjameslee** [comment]
This will be fixed in NAF 0.5. In the meantime you can test that it works here: https://organic-peak.glitch.me/
