### ISSUE TITLE
How to correctly disconnect so I can connect to another room?

### ISSUE THREAD

**Issue by Vamoss** [networked-aframe/networked-aframe#70]
The networked-aframe does not have a destroy/disconnect method, how can I reuse the components and connect to different rooms?
I do not want to reload the entire page because we are trying to use it with a single page app made with Vue.js.

**Comment by antoniohof** [comment]
We tried using window.easyrtc.disconnect() but when reconnecting it it says:

'galleries/16:1 Uncaught (in promise) Attempt to send message without a valid connection to the server.'

**Comment by haydenjameslee** [comment]
I'd like to support this soon, however it currently isn't supported.

**Comment by haydenjameslee** [comment]
I think there's two features here that should be implemented:

1. The ability to disconnect and cleanup NAF completely. This should happen when the `networked-scene` component is removed.

2. The ability to change rooms. This should happen via: `scene.setAttribute('networked-scene', 'room', 'new-room-name');`

**Comment by haydenjameslee** [comment]
I've started a branch for this: https://github.com/networked-aframe/networked-aframe/pull/72

Its nearly working, just running into a some bugs.

**Comment by haydenjameslee** [comment]
Just merged in the disconnect feature to master: https://github.com/networked-aframe/networked-aframe/pull/72

To test it out before we ship v0.5 reference use this: https://raw.githubusercontent.com/networked-aframe/networked-aframe/master/dist/networked-aframe.js

**Comment by haydenjameslee** [comment]
A hacky way to implement switching rooms, now that disconnect (https://github.com/networked-aframe/networked-aframe/pull/72) has been merged, would be to call disconnect, wait x seconds, then connect again as usual. This would mean we don't have to update the adapters to support switching rooms.
