### ISSUE TITLE
how many concurrent users support?

### ISSUE THREAD

**Issue by jyy1082** [networked-aframe/networked-aframe#73]
Is there any clue shows how many concurrent users to support in one room? If we have 100 users in one room, what should we need to pay attention? Thanks.

**Comment by haydenjameslee** [comment]
This depends on a variety of factors, such as what network architecture you're using, how complex your scene is, how much of the scene needs to be synchronized and what devices you need to support. 

I haven't seen any projects pushing this limit yet, so if you create some tests please post them!

**Comment by haydenjameslee** [comment]
What sort of experience do you want to create?

**Comment by jyy1082** [comment]
Thanks for your replay! 
we plan to create a online virtual conference room to allow users to communicate. we will test using this component.

**Comment by jyy1082** [comment]
@haydenjameslee may I ask you that is there a way to sync view? The two functions which we wanna implement: 
1. One room admin can control to make all other participants following admin's view sync. 
2. The room admin can see one participant's view sync to monitor. 
Thanks!

**Comment by haydenjameslee** [comment]
Yes these features are possible to implement. If you want to go into how to do it let's start another thread to keep issues separate.

**Comment by jyy1082** [comment]
That will be great if you can provide the guide to implement! I really appreciate it!

**Comment by haydenjameslee** [comment]
Ok please start another issue or post in the aframe slack's networked-aframe channel.
