### ISSUE TITLE
unable to send message when using easyrtc with audio

### ISSUE THREAD

**Issue by rrrepos** [networked-aframe/networked-aframe#77]
This does not happen always. But frequent enough to cause concern in a production environment. The error that shows up in the javascript console is:

`attempt to send message without a valid connection to the server`.  The debugger shows that it is from: `chrome://devtools/content/webconsole/src/utils/index.js`. This is even when it is run in Firefox.

The only way forward seems to be to exit the scene and reload it. And it always works then.

**Comment by haydenjameslee** [comment]
Are you sending any custom messages (using the [custom message API](https://github.com/networked-aframe/networked-aframe#sending-custom-messages)) or running any network code before the `onConnect` function has been called?

**Comment by rajnikantmrao** [comment]
Yes. In the scene I need to keep track of the position of the user. I internally call it marker. Think of it as the seat where the user is. And the following is the `onConnect` code.

```
onConnect: function() {
      // storing this users id
      _this.clientId = NAF.clientId;

      // updating marker of user
      NAF.connection.subscribeToDataChannel("marker", function(senderId, datatype, data) {

        var userIndex = _this.usersArr.indexOf(senderId);
        if (userIndex == -1) {
          _this.usersArr.push(senderId);
          _this.markersArr.push(data);
        } else {
          _this.markersArr[userIndex] = data;
        }
      });

      // adding to array when new user enters scene
      document.body.addEventListener("clientConnected", function(evt) {
        var userIndex = _this.usersArr.indexOf(evt.detail.clientId);
        if (userIndex == -1) {
          _this.usersArr.push(evt.detail.clientId);
          _this.markersArr.push("");
        } else {
          _this.markersArr[userIndex] = "";
        }
        NAF.connection.sendDataGuaranteed(evt.detail.clientId, "marker", _this.curr_marker)
      });

      // removing from array when user exits scene
      document.body.addEventListener("clientDisconnected", function(evt) {
        var userIndex = _this.usersArr.indexOf(evt.detail.clientId);
        if (userIndex != -1) {
          _this.usersArr.splice(userIndex, 1);
          _this.markersArr.splice(userIndex, 1);
        }
      });
    },
```

And somewhere else when the user decides to move via an event trigger, the following is broadcast: `NAF.connection.broadcastDataGuaranteed("marker", _this.curr_marker);`

**Comment by vincentfretin** [comment]
It's quite old. I'm just going to close it. Please reopen if you still have the issue with open-easyrtc. See #240
