### ISSUE TITLE
Idea: Merge wsEasyRTC adapter with EasyRTC adapter and add webrtc bool to networked-scene

### ISSUE THREAD

**Issue by haydenjameslee** [networked-aframe/networked-aframe#80]
Any WebSocket-only adapter can theoretically do WebRTC without much modification. Once there is a WebSocket connection all the signaling messages can transfer across it and then use WebRTCPeer.js like the [naf-firebase-adapter](https://github.com/networked-aframe/naf-firebase-adapter/tree/master/src) to implement WebRTC.

I'm proposing we add another field to the `networked-scene` schema that allows you to toggle between WebSockets and WebRTC, thus halving the number of adapters we need and making it easier to test different architectures very quickly.

Thoughts?

**Comment by haydenjameslee** [comment]
Ok I made this example real quick: https://github.com/networked-aframe/networked-aframe/pull/81

I don't like how messy it makes [EasyRTCAdapter.js](https://github.com/networked-aframe/networked-aframe/pull/81/files#diff-15d3ea80b33e0826ffcbb0a8e03af7e0).

Maybe this can be cleaned up a lot, but this is probably one of the main reasons I opted for separating the WebSocket adapters into their own files last year...

**Comment by haydenjameslee** [comment]
As far as the API goes, an alternative would be `networked-scene="transport: websocket / webrtc"`

**Comment by haydenjameslee** [comment]
@netpro2k That logic makes sense, I like the idea of `adapterOptions`. I can make a PR for it but if your PR already does some of it I'd be interested to see it. Feel free to make the PR.

**Comment by hthetiot** [comment]
Should be fixed by #175 via Open-EasyRTC latest WebRTCAdapter.js update

**Comment by vincentfretin** [comment]
I know that the janus adapter and now the dialog/mediasoup adapter used by Hubs doesn't use the `audio: bool` param in `networked-scene`, but use `NAF.connection.adapter.enableMicrophone(bool)` to enable an audio track
and @kylebakerio was bite by this because it's not the same API.

**Comment by kylebakerio** [comment]
Going forward, setting options should definitely be unified. While in general I like the idea of just setting whatever adapter options are available in the networked-scene component properties, I _really_ appreciated the simplicity of supplying my chosen stream to janus within the JS, even if it did feel a bit confusing of an API. 

For one example, I wanted to not use the user's mic, but to instead use the audio stream from a tab. Doing that with the Janus adapter was trivial, but doing that with the openeasyrtc adapter required forking the adapter, and had some buggy behavior that I didn't get to the end of.

**Comment by vincentfretin** [comment]
Ok just saw #81 from @haydenjameslee that add a webrtc option to the easyrtc adapter. I don't like it either, so I agree with @haydenjameslee not to merge both adapters.
I agree completely with @netpro2k comment https://github.com/networked-aframe/networked-aframe/issues/80#issuecomment-360659707 about ditching the video and audio flags in favor of setLocalMediaStream as proposed in #57 . And you're right @kylebakerio setLocalMediaStream like it is implemented in the janus adapter is much more flexible, you can share really what you want indeed.
I'll track this as part of adding video support to the easyrtc adapter in #211
Closing this issue.
