### ISSUE TITLE
Unused var `showTemplate`

### ISSUE THREAD

**Issue by johnshaughnessy** [networked-aframe/networked-aframe#82]
Not sure whether the next line wanted to use `showTemplate` or this line is just dead code and can be eliminated:
https://github.com/networked-aframe/networked-aframe/blob/master/src/components/networked.js#L82

**Comment by haydenjameslee** [comment]
Fixed: https://github.com/networked-aframe/networked-aframe/commit/7dc6eee674caea8167a2a3f4cd7429f123db2697
