### ISSUE TITLE
lerping in networked.js no longer correct after ownership transfer feature

### ISSUE THREAD

**Issue by InfiniteLee** [networked-aframe/networked-aframe#87]
`attachLerp()` is called in networked.js is only called if `wasCreatedByNetwork` is true, however because they can change ownership now this is not really a valid check anymore. `attachLerp()` should probably always be called, however the lerping should only be active if the component is not currently owned by the local player.

**Comment by haydenjameslee** [comment]
Fixed in 0.5.1
