### ISSUE TITLE
updating synced objects using third party components

### ISSUE THREAD

**Issue by msimbao** [networked-aframe/networked-aframe#88]
Hi. Your project is awesome and i can't believe all the different stuff you can do with it and the different options it opens up. I wanted to ask if it is possible to continuously update custom entities that are synced using third party components like super-hands or click-drag. I've been trying for a while but can't seem to get the server to update the positions and rotations for the second viewer. Would ownership transfer help with that?

**Comment by msimbao** [comment]
Hi Hayden. thanks for the quick reply! Here's an example which is just a bare-bones remix of your basic naf glitch example.

 https://glitch.com/edit/#!/bio-gas?path=public/index.html

I was trying to sync a box so that it can be dragged by both users or just one and the other is still able to see the action.

**Comment by netpro2k** [comment]
Note that one tricky bit about super-hands in particular is that `aframe-physics-system` uses a `quaternion` component to do its rotation, so you will specifically need to sync that. See https://github.com/mozilla/mr-social-client/blob/experiment/super-hands/src/network-schemas.js#L30

**Comment by msimbao** [comment]
Hi netpro2k, thanks for the response. Adding the quaternion component did help out but apparently the problem was with my code. I just found it and saw that i wasn't adding the progressive-controls component and grabbable components to the correct entities. I was putting them all together but instead had to seperate them. 

   <a-entity  progressive-controls="objects:#mine"></a-entity>
                
      <a-entity id="mine" grabbable networked="template:#box-template;showLocalTemplate:true" position="0 1 0" >
     </a-entity>

I'm still having a problem with syncing and the only way it worked was with a glitch in the java o.o (i think the second square brace shouldn't exist at the end)

 var boxSchema = {
        template: '#box-template',
        components: [
          "position",
          "rotation",
          "scale",
          "rotation",
          "quaternion",
        ]
           
        ]
      };
      NAF.schemas.add(boxSchema);

but ill come figure it out. Thanks so much for all the help!

**Comment by netpro2k** [comment]
You have `rotation` in there twice, you actually don't need it at all since the `quaternion` component actually removes `rotation`. Also you are correct, there is an extra `]`
```
var boxSchema = {
  template: '#box-template',
  components: [
    "position",
    "scale",
    "quaternion"
  ]
};
NAF.schemas.add(boxSchema);
```
