### ISSUE TITLE
Is there a way to auto sync specific var when user connect?

### ISSUE THREAD

**Issue by Vamoss** [networked-aframe/networked-aframe#97]
I have a situation where I don't use an object template because I have a fixed object in the scene. I need to propagate a property to all clients.
Thanks!

**Comment by Vamoss** [comment]
I know I could use `broadcastDataGuaranteed`, but it is hard to handle all the situations like:
> When a new user connects
> When the host changes the property
> When I am the first user and need to configure the property

**Comment by haydenjameslee** [comment]
I would suggest making a custom A-Frame component that stores the property. Then have some way to determine who is the "host" of the room (we will eventually provide a nice way to do with through NAF but it doesn't exist yet) eg. `?host=true` as a url parameter, or work out who has been in the room the longest. Whoever is the host then spawns this entity with the custom component and configures it. This will handle all your situations.
